// Code generated by ffprobe/internal/gen from doc/ffprobe.xsd at FFmpeg tags n4.4.4, n5.1.4, n6.0.1, n6.1.2, n7.0.2, n7.1.3, n8.0, n8.1.2. DO NOT EDIT.

package ffprobe

import "encoding/json"

// SchemaVersions lists the FFmpeg tags whose ffprobe.xsd fed the generated types.
var SchemaVersions = []string{"n4.4.4", "n5.1.4", "n6.0.1", "n6.1.2", "n7.0.2", "n7.1.3", "n8.0", "n8.1.2"}

// Chapter is ffprobe's chapterType.
type Chapter struct {
	// ID is the JSON "id" field.
	ID Int `json:"id,omitzero"`

	// TimeBase is the JSON "time_base" field.
	TimeBase Rat `json:"time_base,omitzero"`

	// Start is the JSON "start" field.
	Start Int `json:"start,omitzero"`

	// StartSecs is the JSON "start_time" field.
	StartSecs Seconds `json:"start_time,omitzero"`

	// End is the JSON "end" field.
	End Int `json:"end,omitzero"`

	// EndSecs is the JSON "end_time" field.
	EndSecs Seconds `json:"end_time,omitzero"`

	// Tags is the JSON "tags" field.
	Tags Tags `json:"tags,omitempty"`
}

// Disposition is ffprobe's streamDispositionType.
type Disposition struct {
	// Default is the JSON "default" field.
	Default Bool `json:"default,omitzero"`

	// Dub is the JSON "dub" field.
	Dub Bool `json:"dub,omitzero"`

	// Original is the JSON "original" field.
	Original Bool `json:"original,omitzero"`

	// Comment is the JSON "comment" field.
	Comment Bool `json:"comment,omitzero"`

	// Lyrics is the JSON "lyrics" field.
	Lyrics Bool `json:"lyrics,omitzero"`

	// Karaoke is the JSON "karaoke" field.
	Karaoke Bool `json:"karaoke,omitzero"`

	// Forced is the JSON "forced" field.
	Forced Bool `json:"forced,omitzero"`

	// HearingImpaired is the JSON "hearing_impaired" field.
	HearingImpaired Bool `json:"hearing_impaired,omitzero"`

	// VisualImpaired is the JSON "visual_impaired" field.
	VisualImpaired Bool `json:"visual_impaired,omitzero"`

	// CleanEffects is the JSON "clean_effects" field.
	CleanEffects Bool `json:"clean_effects,omitzero"`

	// AttachedPic is the JSON "attached_pic" field.
	AttachedPic Bool `json:"attached_pic,omitzero"`

	// TimedThumbnails is the JSON "timed_thumbnails" field.
	TimedThumbnails Bool `json:"timed_thumbnails,omitzero"`

	// Captions is the JSON "captions" field. Added in FFmpeg 5.1.
	Captions Bool `json:"captions,omitzero"`

	// Descriptions is the JSON "descriptions" field. Added in FFmpeg 5.1.
	Descriptions Bool `json:"descriptions,omitzero"`

	// Metadata is the JSON "metadata" field. Added in FFmpeg 5.1.
	Metadata Bool `json:"metadata,omitzero"`

	// Dependent is the JSON "dependent" field. Added in FFmpeg 5.1.
	Dependent Bool `json:"dependent,omitzero"`

	// StillImage is the JSON "still_image" field. Added in FFmpeg 5.1.
	StillImage Bool `json:"still_image,omitzero"`

	// NonDiegetic is the JSON "non_diegetic" field. Added in FFmpeg 6.1.
	NonDiegetic Bool `json:"non_diegetic,omitzero"`

	// Multilayer is the JSON "multilayer" field. Added in FFmpeg 7.1.
	Multilayer Bool `json:"multilayer,omitzero"`
}

// Format is ffprobe's formatType.
type Format struct {
	// Filename is the JSON "filename" field.
	Filename string `json:"filename,omitempty"`

	// NbStreams is the JSON "nb_streams" field.
	NbStreams Int `json:"nb_streams,omitzero"`

	// NbPrograms is the JSON "nb_programs" field.
	NbPrograms Int `json:"nb_programs,omitzero"`

	// FormatName is the JSON "format_name" field.
	FormatName string `json:"format_name,omitempty"`

	// FormatLongName is the JSON "format_long_name" field.
	FormatLongName string `json:"format_long_name,omitempty"`

	// StartSecs is the JSON "start_time" field.
	StartSecs Seconds `json:"start_time,omitzero"`

	// DurationSecs is the JSON "duration" field.
	DurationSecs Seconds `json:"duration,omitzero"`

	// Size is the JSON "size" field.
	Size Int `json:"size,omitzero"`

	// BitRate is the JSON "bit_rate" field.
	BitRate Int `json:"bit_rate,omitzero"`

	// ProbeScore is the JSON "probe_score" field.
	ProbeScore Int `json:"probe_score,omitzero"`

	// NbStreamGroups is the JSON "nb_stream_groups" field. Added in FFmpeg 7.0.
	NbStreamGroups Int `json:"nb_stream_groups,omitzero"`

	// Tags is the JSON "tags" field.
	Tags Tags `json:"tags,omitempty"`
}

// Frame is ffprobe's frameType.
// Subtitle frames (media_type "subtitle") use the same struct; their
// fields are marked below.
type Frame struct {
	// MediaType is the JSON "media_type" field.
	MediaType string `json:"media_type,omitempty"`

	// StreamIndex is the JSON "stream_index" field.
	StreamIndex Int `json:"stream_index,omitzero"`

	// KeyFrame is the JSON "key_frame" field.
	KeyFrame Bool `json:"key_frame,omitzero"`

	// PTS is the JSON "pts" field.
	PTS Int `json:"pts,omitzero"`

	// PTSSecs is the JSON "pts_time" field.
	PTSSecs Seconds `json:"pts_time,omitzero"`

	// PktPTS is the JSON "pkt_pts" field. Dropped from the XSD after FFmpeg 4.4 but still printed in JSON.
	PktPTS Int `json:"pkt_pts,omitzero"`

	// PktPTSSecs is the JSON "pkt_pts_time" field. Dropped from the XSD after FFmpeg 4.4 but still printed in JSON.
	PktPTSSecs Seconds `json:"pkt_pts_time,omitzero"`

	// PktDTS is the JSON "pkt_dts" field.
	PktDTS Int `json:"pkt_dts,omitzero"`

	// PktDTSSecs is the JSON "pkt_dts_time" field.
	PktDTSSecs Seconds `json:"pkt_dts_time,omitzero"`

	// BestEffortTimestamp is the JSON "best_effort_timestamp" field.
	BestEffortTimestamp Int `json:"best_effort_timestamp,omitzero"`

	// BestEffortTimestampSecs is the JSON "best_effort_timestamp_time" field.
	BestEffortTimestampSecs Seconds `json:"best_effort_timestamp_time,omitzero"`

	// PktDuration is the JSON "pkt_duration" field. Dropped from the XSD after FFmpeg 6.1 but still printed in JSON.
	PktDuration Int `json:"pkt_duration,omitzero"`

	// PktDurationSecs is the JSON "pkt_duration_time" field. Dropped from the XSD after FFmpeg 6.1 but still printed in JSON.
	PktDurationSecs Seconds `json:"pkt_duration_time,omitzero"`

	// PktPos is the JSON "pkt_pos" field.
	PktPos Int `json:"pkt_pos,omitzero"`

	// PktSize is the JSON "pkt_size" field.
	PktSize Int `json:"pkt_size,omitzero"`

	// SampleFmt is the JSON "sample_fmt" field.
	SampleFmt string `json:"sample_fmt,omitempty"`

	// NbSamples is the JSON "nb_samples" field.
	NbSamples Int `json:"nb_samples,omitzero"`

	// Channels is the JSON "channels" field.
	Channels Int `json:"channels,omitzero"`

	// ChannelLayout is the JSON "channel_layout" field.
	ChannelLayout string `json:"channel_layout,omitempty"`

	// Width is the JSON "width" field.
	Width Int `json:"width,omitzero"`

	// Height is the JSON "height" field.
	Height Int `json:"height,omitzero"`

	// PixFmt is the JSON "pix_fmt" field.
	PixFmt string `json:"pix_fmt,omitempty"`

	// SampleAspectRatio is the JSON "sample_aspect_ratio" field.
	SampleAspectRatio Rat `json:"sample_aspect_ratio,omitzero"`

	// PictType is the JSON "pict_type" field.
	PictType string `json:"pict_type,omitempty"`

	// CodedPictureNumber is the JSON "coded_picture_number" field. Dropped from the XSD after FFmpeg 6.1 but still printed in JSON.
	CodedPictureNumber Int `json:"coded_picture_number,omitzero"`

	// DisplayPictureNumber is the JSON "display_picture_number" field. Dropped from the XSD after FFmpeg 6.1 but still printed in JSON.
	DisplayPictureNumber Int `json:"display_picture_number,omitzero"`

	// InterlacedFrame is the JSON "interlaced_frame" field.
	InterlacedFrame Bool `json:"interlaced_frame,omitzero"`

	// TopFieldFirst is the JSON "top_field_first" field.
	TopFieldFirst Bool `json:"top_field_first,omitzero"`

	// RepeatPict is the JSON "repeat_pict" field.
	RepeatPict Int `json:"repeat_pict,omitzero"`

	// ColorRange is the JSON "color_range" field.
	ColorRange string `json:"color_range,omitempty"`

	// ColorSpace is the JSON "color_space" field.
	ColorSpace string `json:"color_space,omitempty"`

	// ColorPrimaries is the JSON "color_primaries" field.
	ColorPrimaries string `json:"color_primaries,omitempty"`

	// ColorTransfer is the JSON "color_transfer" field.
	ColorTransfer string `json:"color_transfer,omitempty"`

	// ChromaLocation is the JSON "chroma_location" field.
	ChromaLocation string `json:"chroma_location,omitempty"`

	// DurationTS is the JSON "duration" field. Added in FFmpeg 6.0.
	DurationTS Int `json:"duration,omitzero"`

	// DurationSecs is the JSON "duration_time" field. Added in FFmpeg 6.0.
	DurationSecs Seconds `json:"duration_time,omitzero"`

	// CropTop is the JSON "crop_top" field. Added in FFmpeg 6.1.
	CropTop Int `json:"crop_top,omitzero"`

	// CropBottom is the JSON "crop_bottom" field. Added in FFmpeg 6.1.
	CropBottom Int `json:"crop_bottom,omitzero"`

	// CropLeft is the JSON "crop_left" field. Added in FFmpeg 6.1.
	CropLeft Int `json:"crop_left,omitzero"`

	// CropRight is the JSON "crop_right" field. Added in FFmpeg 6.1.
	CropRight Int `json:"crop_right,omitzero"`

	// Lossless is the JSON "lossless" field. Added in FFmpeg 8.0.
	Lossless Bool `json:"lossless,omitzero"`

	// Format is the JSON "format" field. Subtitle frames only.
	Format Int `json:"format,omitzero"`

	// StartDisplayTime is the JSON "start_display_time" field. Subtitle frames only.
	StartDisplayTime Int `json:"start_display_time,omitzero"`

	// EndDisplayTime is the JSON "end_display_time" field. Subtitle frames only.
	EndDisplayTime Int `json:"end_display_time,omitzero"`

	// NumRects is the JSON "num_rects" field. Subtitle frames only.
	NumRects Int `json:"num_rects,omitzero"`

	// Logs is the JSON "logs" field.
	Logs []*Log `json:"logs,omitempty"`

	// SideDataList is the JSON "side_data_list" field.
	SideDataList []*FrameSideData `json:"side_data_list,omitempty"`

	// Tags is the JSON "tags" field.
	Tags Tags `json:"tags,omitempty"`
}

// FrameSideData is ffprobe's frameSideDataType.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type FrameSideData struct {
	// SideDataType is the JSON "side_data_type" field.
	SideDataType string `json:"side_data_type,omitempty"`

	// SideDataSize is the JSON "side_data_size" field.
	SideDataSize Int `json:"side_data_size,omitzero"`

	// Timecode is the JSON "timecode" field.
	Timecode string `json:"timecode,omitempty"`

	// Timecodes is the JSON "timecodes" field.
	Timecodes []*FrameSideDataTimecode `json:"timecodes,omitempty"`

	// Components is the JSON "components" field. Added in FFmpeg 7.0.
	Components []*FrameSideDataComponent `json:"components,omitempty"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var frameSideDataKnownKeys = map[string]bool{"side_data_type": true, "side_data_size": true, "timecode": true, "timecodes": true, "components": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *FrameSideData) UnmarshalJSON(data []byte) error {
	type plain FrameSideData
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, frameSideDataKnownKeys)
	if err != nil {
		return err
	}
	*v = FrameSideData(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v FrameSideData) MarshalJSON() ([]byte, error) {
	type plain FrameSideData
	return encodeExtra(plain(v), v.Extra)
}

// FrameSideDataComponent is ffprobe's frameSideDataComponentType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type FrameSideDataComponent struct {
	// Pieces is the JSON "pieces" field. Added in FFmpeg 7.0.
	Pieces []*FrameSideDataPiece `json:"pieces,omitempty"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var frameSideDataComponentKnownKeys = map[string]bool{"pieces": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *FrameSideDataComponent) UnmarshalJSON(data []byte) error {
	type plain FrameSideDataComponent
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, frameSideDataComponentKnownKeys)
	if err != nil {
		return err
	}
	*v = FrameSideDataComponent(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v FrameSideDataComponent) MarshalJSON() ([]byte, error) {
	type plain FrameSideDataComponent
	return encodeExtra(plain(v), v.Extra)
}

// FrameSideDataPiece is ffprobe's frameSideDataPieceType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type FrameSideDataPiece struct {
	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var frameSideDataPieceKnownKeys = map[string]bool{}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *FrameSideDataPiece) UnmarshalJSON(data []byte) error {
	type plain FrameSideDataPiece
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, frameSideDataPieceKnownKeys)
	if err != nil {
		return err
	}
	*v = FrameSideDataPiece(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v FrameSideDataPiece) MarshalJSON() ([]byte, error) {
	type plain FrameSideDataPiece
	return encodeExtra(plain(v), v.Extra)
}

// FrameSideDataTimecode is ffprobe's frameSideDataTimecodeType.
type FrameSideDataTimecode struct {
	// Value is the JSON "value" field.
	Value string `json:"value,omitempty"`
}

// LibraryVersion is ffprobe's libraryVersionType.
type LibraryVersion struct {
	// Name is the JSON "name" field.
	Name string `json:"name,omitempty"`

	// Major is the JSON "major" field.
	Major Int `json:"major,omitzero"`

	// Minor is the JSON "minor" field.
	Minor Int `json:"minor,omitzero"`

	// Micro is the JSON "micro" field.
	Micro Int `json:"micro,omitzero"`

	// Version is the JSON "version" field.
	Version Int `json:"version,omitzero"`

	// Ident is the JSON "ident" field.
	Ident string `json:"ident,omitempty"`
}

// Log is ffprobe's logType.
type Log struct {
	// Context is the JSON "context" field.
	Context string `json:"context,omitempty"`

	// Level is the JSON "level" field.
	Level Int `json:"level,omitzero"`

	// Category is the JSON "category" field.
	Category Int `json:"category,omitzero"`

	// ParentContext is the JSON "parent_context" field.
	ParentContext string `json:"parent_context,omitempty"`

	// ParentCategory is the JSON "parent_category" field.
	ParentCategory Int `json:"parent_category,omitzero"`

	// Message is the JSON "message" field.
	Message string `json:"message,omitempty"`
}

// Packet is ffprobe's packetType.
type Packet struct {
	// CodecType is the JSON "codec_type" field.
	CodecType string `json:"codec_type,omitempty"`

	// StreamIndex is the JSON "stream_index" field.
	StreamIndex Int `json:"stream_index,omitzero"`

	// PTS is the JSON "pts" field.
	PTS Int `json:"pts,omitzero"`

	// PTSSecs is the JSON "pts_time" field.
	PTSSecs Seconds `json:"pts_time,omitzero"`

	// DTS is the JSON "dts" field.
	DTS Int `json:"dts,omitzero"`

	// DTSSecs is the JSON "dts_time" field.
	DTSSecs Seconds `json:"dts_time,omitzero"`

	// DurationTS is the JSON "duration" field.
	DurationTS Int `json:"duration,omitzero"`

	// DurationSecs is the JSON "duration_time" field.
	DurationSecs Seconds `json:"duration_time,omitzero"`

	// Size is the JSON "size" field.
	Size Int `json:"size,omitzero"`

	// Pos is the JSON "pos" field.
	Pos Int `json:"pos,omitzero"`

	// Flags is the JSON "flags" field.
	Flags string `json:"flags,omitempty"`

	// Data is the JSON "data" field.
	Data string `json:"data,omitempty"`

	// DataHash is the JSON "data_hash" field.
	DataHash string `json:"data_hash,omitempty"`

	// SideDataList is the JSON "side_data_list" field.
	SideDataList []*SideData `json:"side_data_list,omitempty"`

	// Tags is the JSON "tags" field.
	Tags Tags `json:"tags,omitempty"`
}

// PixelFormat is ffprobe's pixelFormatType.
type PixelFormat struct {
	// Name is the JSON "name" field.
	Name string `json:"name,omitempty"`

	// NbComponents is the JSON "nb_components" field.
	NbComponents Int `json:"nb_components,omitzero"`

	// Log2ChromaW is the JSON "log2_chroma_w" field.
	Log2ChromaW Int `json:"log2_chroma_w,omitzero"`

	// Log2ChromaH is the JSON "log2_chroma_h" field.
	Log2ChromaH Int `json:"log2_chroma_h,omitzero"`

	// BitsPerPixel is the JSON "bits_per_pixel" field.
	BitsPerPixel Int `json:"bits_per_pixel,omitzero"`

	// Flags is the JSON "flags" field.
	Flags PixelFormatFlags `json:"flags,omitzero"`

	// Components is the JSON "components" field.
	Components []*PixelFormatComponent `json:"components,omitempty"`
}

// PixelFormatComponent is ffprobe's pixelFormatComponentType.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type PixelFormatComponent struct {
	// Index is the JSON "index" field.
	Index Int `json:"index,omitzero"`

	// BitDepth is the JSON "bit_depth" field.
	BitDepth Int `json:"bit_depth,omitzero"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var pixelFormatComponentKnownKeys = map[string]bool{"index": true, "bit_depth": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *PixelFormatComponent) UnmarshalJSON(data []byte) error {
	type plain PixelFormatComponent
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, pixelFormatComponentKnownKeys)
	if err != nil {
		return err
	}
	*v = PixelFormatComponent(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v PixelFormatComponent) MarshalJSON() ([]byte, error) {
	type plain PixelFormatComponent
	return encodeExtra(plain(v), v.Extra)
}

// PixelFormatFlags is ffprobe's pixelFormatFlagsType.
type PixelFormatFlags struct {
	// BigEndian is the JSON "big_endian" field.
	BigEndian Bool `json:"big_endian,omitzero"`

	// Palette is the JSON "palette" field.
	Palette Bool `json:"palette,omitzero"`

	// Bitstream is the JSON "bitstream" field.
	Bitstream Bool `json:"bitstream,omitzero"`

	// Hwaccel is the JSON "hwaccel" field.
	Hwaccel Bool `json:"hwaccel,omitzero"`

	// Planar is the JSON "planar" field.
	Planar Bool `json:"planar,omitzero"`

	// Rgb is the JSON "rgb" field.
	Rgb Bool `json:"rgb,omitzero"`

	// Alpha is the JSON "alpha" field.
	Alpha Bool `json:"alpha,omitzero"`
}

// ProbeError is ffprobe's errorType.
type ProbeError struct {
	// Code is the JSON "code" field.
	Code AVError `json:"code,omitzero"`

	// Message is the JSON "string" field.
	Message string `json:"string,omitempty"`
}

// Program is ffprobe's programType.
type Program struct {
	// ProgramID is the JSON "program_id" field.
	ProgramID Int `json:"program_id,omitzero"`

	// ProgramNum is the JSON "program_num" field.
	ProgramNum Int `json:"program_num,omitzero"`

	// NbStreams is the JSON "nb_streams" field.
	NbStreams Int `json:"nb_streams,omitzero"`

	// StartSecs is the JSON "start_time" field. Dropped from the XSD after FFmpeg 4.4 but still printed in JSON.
	StartSecs Seconds `json:"start_time,omitzero"`

	// StartPTS is the JSON "start_pts" field. Dropped from the XSD after FFmpeg 4.4 but still printed in JSON.
	StartPTS Int `json:"start_pts,omitzero"`

	// EndSecs is the JSON "end_time" field. Dropped from the XSD after FFmpeg 4.4 but still printed in JSON.
	EndSecs Seconds `json:"end_time,omitzero"`

	// EndPTS is the JSON "end_pts" field. Dropped from the XSD after FFmpeg 4.4 but still printed in JSON.
	EndPTS Int `json:"end_pts,omitzero"`

	// PmtPid is the JSON "pmt_pid" field.
	PmtPid Int `json:"pmt_pid,omitzero"`

	// PcrPid is the JSON "pcr_pid" field.
	PcrPid Int `json:"pcr_pid,omitzero"`

	// Streams is the JSON "streams" field.
	Streams []*Stream `json:"streams,omitempty"`

	// Tags is the JSON "tags" field.
	Tags Tags `json:"tags,omitempty"`
}

// ProgramVersion is ffprobe's programVersionType.
type ProgramVersion struct {
	// Version is the JSON "version" field.
	Version string `json:"version,omitempty"`

	// Copyright is the JSON "copyright" field.
	Copyright string `json:"copyright,omitempty"`

	// BuildDate is the JSON "build_date" field.
	BuildDate string `json:"build_date,omitempty"`

	// BuildTime is the JSON "build_time" field.
	BuildTime string `json:"build_time,omitempty"`

	// CompilerIdent is the JSON "compiler_ident" field.
	CompilerIdent string `json:"compiler_ident,omitempty"`

	// Configuration is the JSON "configuration" field.
	Configuration string `json:"configuration,omitempty"`
}

// Result is ffprobe's ffprobeType.
type Result struct {
	// ProgramVersion is the JSON "program_version" field.
	ProgramVersion ProgramVersion `json:"program_version,omitzero"`

	// LibraryVersions is the JSON "library_versions" field.
	LibraryVersions []*LibraryVersion `json:"library_versions,omitempty"`

	// PixelFormats is the JSON "pixel_formats" field.
	PixelFormats []*PixelFormat `json:"pixel_formats,omitempty"`

	// Packets is the JSON "packets" field.
	Packets []*Packet `json:"packets,omitempty"`

	// Frames is the JSON "frames" field.
	Frames []*Frame `json:"frames,omitempty"`

	// PacketsAndFrames is the JSON "packets_and_frames" field.
	PacketsAndFrames []PacketOrFrame `json:"packets_and_frames,omitempty"`

	// Programs is the JSON "programs" field.
	Programs []*Program `json:"programs,omitempty"`

	// Streams is the JSON "streams" field.
	Streams []*Stream `json:"streams,omitempty"`

	// Chapters is the JSON "chapters" field.
	Chapters []*Chapter `json:"chapters,omitempty"`

	// Format is the JSON "format" field.
	Format Format `json:"format,omitzero"`

	// Error is the JSON "error" field.
	Error *ProbeError `json:"error,omitempty"`

	// StreamGroups is the JSON "stream_groups" field. Added in FFmpeg 7.0.
	StreamGroups []*StreamGroup `json:"stream_groups,omitempty"`
}

// SideData is ffprobe's packetSideDataType.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type SideData struct {
	// SideDataType is the JSON "side_data_type" field. Dropped from the XSD after FFmpeg 6.0 but still printed in JSON.
	SideDataType string `json:"side_data_type,omitempty"`

	// SideDataSize is the JSON "side_data_size" field. Removed after FFmpeg 6.0.
	SideDataSize Int `json:"side_data_size,omitzero"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var sideDataKnownKeys = map[string]bool{"side_data_type": true, "side_data_size": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *SideData) UnmarshalJSON(data []byte) error {
	type plain SideData
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, sideDataKnownKeys)
	if err != nil {
		return err
	}
	*v = SideData(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v SideData) MarshalJSON() ([]byte, error) {
	type plain SideData
	return encodeExtra(plain(v), v.Extra)
}

// Stream is ffprobe's streamType.
type Stream struct {
	// Index is the JSON "index" field.
	Index Int `json:"index,omitzero"`

	// CodecName is the JSON "codec_name" field.
	CodecName string `json:"codec_name,omitempty"`

	// CodecLongName is the JSON "codec_long_name" field.
	CodecLongName string `json:"codec_long_name,omitempty"`

	// Profile is the JSON "profile" field.
	Profile string `json:"profile,omitempty"`

	// CodecType is the JSON "codec_type" field.
	CodecType string `json:"codec_type,omitempty"`

	// CodecTag is the JSON "codec_tag" field.
	CodecTag string `json:"codec_tag,omitempty"`

	// CodecTagString is the JSON "codec_tag_string" field.
	CodecTagString string `json:"codec_tag_string,omitempty"`

	// Extradata is the JSON "extradata" field.
	Extradata string `json:"extradata,omitempty"`

	// ExtradataHash is the JSON "extradata_hash" field.
	ExtradataHash string `json:"extradata_hash,omitempty"`

	// Width is the JSON "width" field.
	Width Int `json:"width,omitzero"`

	// Height is the JSON "height" field.
	Height Int `json:"height,omitzero"`

	// CodedWidth is the JSON "coded_width" field.
	CodedWidth Int `json:"coded_width,omitzero"`

	// CodedHeight is the JSON "coded_height" field.
	CodedHeight Int `json:"coded_height,omitzero"`

	// ClosedCaptions is the JSON "closed_captions" field.
	ClosedCaptions Bool `json:"closed_captions,omitzero"`

	// HasBFrames is the JSON "has_b_frames" field.
	HasBFrames Int `json:"has_b_frames,omitzero"`

	// SampleAspectRatio is the JSON "sample_aspect_ratio" field.
	SampleAspectRatio Rat `json:"sample_aspect_ratio,omitzero"`

	// DisplayAspectRatio is the JSON "display_aspect_ratio" field.
	DisplayAspectRatio Rat `json:"display_aspect_ratio,omitzero"`

	// PixFmt is the JSON "pix_fmt" field.
	PixFmt string `json:"pix_fmt,omitempty"`

	// Level is the JSON "level" field.
	Level Int `json:"level,omitzero"`

	// ColorRange is the JSON "color_range" field.
	ColorRange string `json:"color_range,omitempty"`

	// ColorSpace is the JSON "color_space" field.
	ColorSpace string `json:"color_space,omitempty"`

	// ColorTransfer is the JSON "color_transfer" field.
	ColorTransfer string `json:"color_transfer,omitempty"`

	// ColorPrimaries is the JSON "color_primaries" field.
	ColorPrimaries string `json:"color_primaries,omitempty"`

	// ChromaLocation is the JSON "chroma_location" field.
	ChromaLocation string `json:"chroma_location,omitempty"`

	// FieldOrder is the JSON "field_order" field.
	FieldOrder string `json:"field_order,omitempty"`

	// Refs is the JSON "refs" field.
	Refs Int `json:"refs,omitzero"`

	// SampleFmt is the JSON "sample_fmt" field.
	SampleFmt string `json:"sample_fmt,omitempty"`

	// SampleRate is the JSON "sample_rate" field.
	SampleRate Int `json:"sample_rate,omitzero"`

	// Channels is the JSON "channels" field.
	Channels Int `json:"channels,omitzero"`

	// ChannelLayout is the JSON "channel_layout" field.
	ChannelLayout string `json:"channel_layout,omitempty"`

	// BitsPerSample is the JSON "bits_per_sample" field.
	BitsPerSample Int `json:"bits_per_sample,omitzero"`

	// ID is the JSON "id" field.
	ID string `json:"id,omitempty"`

	// RFrameRate is the JSON "r_frame_rate" field.
	RFrameRate Rat `json:"r_frame_rate,omitzero"`

	// AvgFrameRate is the JSON "avg_frame_rate" field.
	AvgFrameRate Rat `json:"avg_frame_rate,omitzero"`

	// TimeBase is the JSON "time_base" field.
	TimeBase Rat `json:"time_base,omitzero"`

	// StartPTS is the JSON "start_pts" field.
	StartPTS Int `json:"start_pts,omitzero"`

	// StartSecs is the JSON "start_time" field.
	StartSecs Seconds `json:"start_time,omitzero"`

	// DurationTS is the JSON "duration_ts" field.
	DurationTS Int `json:"duration_ts,omitzero"`

	// DurationSecs is the JSON "duration" field.
	DurationSecs Seconds `json:"duration,omitzero"`

	// BitRate is the JSON "bit_rate" field.
	BitRate Int `json:"bit_rate,omitzero"`

	// MaxBitRate is the JSON "max_bit_rate" field.
	MaxBitRate Int `json:"max_bit_rate,omitzero"`

	// BitsPerRawSample is the JSON "bits_per_raw_sample" field.
	BitsPerRawSample Int `json:"bits_per_raw_sample,omitzero"`

	// NbFrames is the JSON "nb_frames" field.
	NbFrames Int `json:"nb_frames,omitzero"`

	// NbReadFrames is the JSON "nb_read_frames" field.
	NbReadFrames Int `json:"nb_read_frames,omitzero"`

	// NbReadPackets is the JSON "nb_read_packets" field.
	NbReadPackets Int `json:"nb_read_packets,omitzero"`

	// ExtradataSize is the JSON "extradata_size" field. Added in FFmpeg 5.1.
	ExtradataSize Int `json:"extradata_size,omitzero"`

	// FilmGrain is the JSON "film_grain" field. Added in FFmpeg 5.1.
	FilmGrain Bool `json:"film_grain,omitzero"`

	// InitialPadding is the JSON "initial_padding" field. Added in FFmpeg 6.0.
	InitialPadding Int `json:"initial_padding,omitzero"`

	// MimeCodecString is the JSON "mime_codec_string" field. Added in FFmpeg 8.1.
	MimeCodecString string `json:"mime_codec_string,omitempty"`

	// ViewIdsAvailable is the JSON "view_ids_available" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 7.1.
	ViewIdsAvailable string `json:"view_ids_available,omitempty"`

	// ViewPosAvailable is the JSON "view_pos_available" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 7.1.
	ViewPosAvailable string `json:"view_pos_available,omitempty"`

	// TSID is the JSON "ts_id" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 7.1.
	TSID Int `json:"ts_id,omitzero"`

	// TSPacketsize is the JSON "ts_packetsize" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 6.1.
	TSPacketsize Int `json:"ts_packetsize,omitzero"`

	// IsAvc is the JSON "is_avc" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 4.4.
	IsAvc Bool `json:"is_avc,omitzero"`

	// NalLengthSize is the JSON "nal_length_size" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 4.4.
	NalLengthSize Int `json:"nal_length_size,omitzero"`

	// Disposition is the JSON "disposition" field.
	Disposition Disposition `json:"disposition,omitzero"`

	// SideDataList is the JSON "side_data_list" field.
	SideDataList []*SideData `json:"side_data_list,omitempty"`

	// Tags is the JSON "tags" field.
	Tags Tags `json:"tags,omitempty"`
}

// StreamGroup is ffprobe's streamGroupType. Added in FFmpeg 7.0.
type StreamGroup struct {
	// Index is the JSON "index" field. Added in FFmpeg 7.0.
	Index Int `json:"index,omitzero"`

	// NbStreams is the JSON "nb_streams" field. Added in FFmpeg 7.0.
	NbStreams Int `json:"nb_streams,omitzero"`

	// Type is the JSON "type" field. Added in FFmpeg 7.0.
	Type string `json:"type,omitempty"`

	// ID is the JSON "id" field. Not listed in the XSD; observed in JSON output. Added in FFmpeg 7.0.
	ID string `json:"id,omitempty"`

	// Disposition is the JSON "disposition" field. Added in FFmpeg 7.0.
	Disposition Disposition `json:"disposition,omitzero"`

	// Tags is the JSON "tags" field. Added in FFmpeg 7.0.
	Tags Tags `json:"tags,omitempty"`

	// Streams is the JSON "streams" field. Added in FFmpeg 7.0.
	Streams []*Stream `json:"streams,omitempty"`

	// Components is the JSON "components" field. Added in FFmpeg 7.0.
	Components []*StreamGroupComponent `json:"components,omitempty"`
}

// StreamGroupBlock is ffprobe's streamGroupBlockType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type StreamGroupBlock struct {
	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var streamGroupBlockKnownKeys = map[string]bool{}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *StreamGroupBlock) UnmarshalJSON(data []byte) error {
	type plain StreamGroupBlock
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, streamGroupBlockKnownKeys)
	if err != nil {
		return err
	}
	*v = StreamGroupBlock(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v StreamGroupBlock) MarshalJSON() ([]byte, error) {
	type plain StreamGroupBlock
	return encodeExtra(plain(v), v.Extra)
}

// StreamGroupComponent is ffprobe's streamGroupComponentType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type StreamGroupComponent struct {
	// Subcomponents is the JSON "subcomponents" field. Added in FFmpeg 7.0.
	Subcomponents []*StreamGroupSubComponent `json:"subcomponents,omitempty"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var streamGroupComponentKnownKeys = map[string]bool{"subcomponents": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *StreamGroupComponent) UnmarshalJSON(data []byte) error {
	type plain StreamGroupComponent
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, streamGroupComponentKnownKeys)
	if err != nil {
		return err
	}
	*v = StreamGroupComponent(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v StreamGroupComponent) MarshalJSON() ([]byte, error) {
	type plain StreamGroupComponent
	return encodeExtra(plain(v), v.Extra)
}

// StreamGroupPiece is ffprobe's streamGroupPieceType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type StreamGroupPiece struct {
	// Subpieces is the JSON "subpieces" field. Added in FFmpeg 7.0.
	Subpieces []*StreamGroupSubPiece `json:"subpieces,omitempty"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var streamGroupPieceKnownKeys = map[string]bool{"subpieces": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *StreamGroupPiece) UnmarshalJSON(data []byte) error {
	type plain StreamGroupPiece
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, streamGroupPieceKnownKeys)
	if err != nil {
		return err
	}
	*v = StreamGroupPiece(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v StreamGroupPiece) MarshalJSON() ([]byte, error) {
	type plain StreamGroupPiece
	return encodeExtra(plain(v), v.Extra)
}

// StreamGroupSubComponent is ffprobe's streamGroupSubComponentType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type StreamGroupSubComponent struct {
	// Pieces is the JSON "pieces" field. Added in FFmpeg 7.0.
	Pieces []*StreamGroupPiece `json:"pieces,omitempty"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var streamGroupSubComponentKnownKeys = map[string]bool{"pieces": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *StreamGroupSubComponent) UnmarshalJSON(data []byte) error {
	type plain StreamGroupSubComponent
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, streamGroupSubComponentKnownKeys)
	if err != nil {
		return err
	}
	*v = StreamGroupSubComponent(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v StreamGroupSubComponent) MarshalJSON() ([]byte, error) {
	type plain StreamGroupSubComponent
	return encodeExtra(plain(v), v.Extra)
}

// StreamGroupSubPiece is ffprobe's streamGroupSubPieceType. Added in FFmpeg 7.0.
//
// ffprobe prints additional keys here that vary by content; they are
// collected in Extra.
type StreamGroupSubPiece struct {
	// Blocks is the JSON "blocks" field. Added in FFmpeg 7.0.
	Blocks []*StreamGroupBlock `json:"blocks,omitempty"`

	// Extra holds every key ffprobe printed that is not a named field above.
	Extra map[string]any `json:"-"`
}

var streamGroupSubPieceKnownKeys = map[string]bool{"blocks": true}

// UnmarshalJSON decodes the named fields and stores every other key in Extra.
func (v *StreamGroupSubPiece) UnmarshalJSON(data []byte) error {
	type plain StreamGroupSubPiece
	var p plain
	if err := json.Unmarshal(data, &p); err != nil {
		return err
	}
	extra, err := decodeExtra(data, streamGroupSubPieceKnownKeys)
	if err != nil {
		return err
	}
	*v = StreamGroupSubPiece(p)
	v.Extra = extra
	return nil
}

// MarshalJSON emits the named fields followed by the keys in Extra.
func (v StreamGroupSubPiece) MarshalJSON() ([]byte, error) {
	type plain StreamGroupSubPiece
	return encodeExtra(plain(v), v.Extra)
}
