// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package ffprobe

import "encoding/json"
import "errors"
import "fmt"

type ChapterType struct {
	// End corresponds to the JSON schema field "end".
	End int `json:"end" yaml:"end" mapstructure:"end"`

	// EndTime corresponds to the JSON schema field "end_time".
	EndTime float64 `json:"end_time" yaml:"end_time" mapstructure:"end_time"`

	// Id corresponds to the JSON schema field "id".
	Id int `json:"id" yaml:"id" mapstructure:"id"`

	// Start corresponds to the JSON schema field "start".
	Start int `json:"start" yaml:"start" mapstructure:"start"`

	// StartTime corresponds to the JSON schema field "start_time".
	StartTime *float64 `json:"start_time,omitempty,omitzero" yaml:"start_time,omitempty" mapstructure:"start_time,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TimeBase corresponds to the JSON schema field "time_base".
	TimeBase string `json:"time_base" yaml:"time_base" mapstructure:"time_base"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChapterType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["end"]; raw != nil && !ok {
		return fmt.Errorf("field end in ChapterType: required")
	}
	if _, ok := raw["end_time"]; raw != nil && !ok {
		return fmt.Errorf("field end_time in ChapterType: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ChapterType: required")
	}
	if _, ok := raw["start"]; raw != nil && !ok {
		return fmt.Errorf("field start in ChapterType: required")
	}
	if _, ok := raw["time_base"]; raw != nil && !ok {
		return fmt.Errorf("field time_base in ChapterType: required")
	}
	type Plain ChapterType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ChapterType(plain)
	return nil
}

type ChaptersType struct {
	// Chapter corresponds to the JSON schema field "chapter".
	Chapter []ChapterType `json:"chapter,omitempty,omitzero" yaml:"chapter,omitempty" mapstructure:"chapter,omitempty"`
}

type ErrorType struct {
	// Code corresponds to the JSON schema field "code".
	Code int `json:"code" yaml:"code" mapstructure:"code"`

	// String corresponds to the JSON schema field "string".
	String string `json:"string" yaml:"string" mapstructure:"string"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ErrorType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in ErrorType: required")
	}
	if _, ok := raw["string"]; raw != nil && !ok {
		return fmt.Errorf("field string in ErrorType: required")
	}
	type Plain ErrorType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ErrorType(plain)
	return nil
}

type FfprobeType struct {
	// Chapters corresponds to the JSON schema field "chapters".
	Chapters []ChapterType `json:"chapters,omitempty,omitzero" yaml:"chapters,omitempty" mapstructure:"chapters,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *ErrorType `json:"error,omitempty,omitzero" yaml:"error,omitempty" mapstructure:"error,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format *FormatType `json:"format,omitempty,omitzero" yaml:"format,omitempty" mapstructure:"format,omitempty"`

	// Frames corresponds to the JSON schema field "frames".
	Frames []FfprobeTypeFramesElem `json:"frames,omitempty,omitzero" yaml:"frames,omitempty" mapstructure:"frames,omitempty"`

	// LibraryVersions corresponds to the JSON schema field "library_versions".
	LibraryVersions []LibraryVersionType `json:"library_versions,omitempty,omitzero" yaml:"library_versions,omitempty" mapstructure:"library_versions,omitempty"`

	// Packets corresponds to the JSON schema field "packets".
	Packets []PacketType `json:"packets,omitempty,omitzero" yaml:"packets,omitempty" mapstructure:"packets,omitempty"`

	// PacketsAndFrames corresponds to the JSON schema field "packets_and_frames".
	PacketsAndFrames []FfprobeTypePacketsAndFramesElem `json:"packets_and_frames,omitempty,omitzero" yaml:"packets_and_frames,omitempty" mapstructure:"packets_and_frames,omitempty"`

	// PixelFormats corresponds to the JSON schema field "pixel_formats".
	PixelFormats []PixelFormatType `json:"pixel_formats,omitempty,omitzero" yaml:"pixel_formats,omitempty" mapstructure:"pixel_formats,omitempty"`

	// ProgramVersion corresponds to the JSON schema field "program_version".
	ProgramVersion *ProgramVersionType `json:"program_version,omitempty,omitzero" yaml:"program_version,omitempty" mapstructure:"program_version,omitempty"`

	// Programs corresponds to the JSON schema field "programs".
	Programs []ProgramType `json:"programs,omitempty,omitzero" yaml:"programs,omitempty" mapstructure:"programs,omitempty"`

	// StreamGroups corresponds to the JSON schema field "stream_groups".
	StreamGroups []StreamGroupType `json:"stream_groups,omitempty,omitzero" yaml:"stream_groups,omitempty" mapstructure:"stream_groups,omitempty"`

	// Streams corresponds to the JSON schema field "streams".
	Streams []StreamType `json:"streams,omitempty,omitzero" yaml:"streams,omitempty" mapstructure:"streams,omitempty"`
}

type FfprobeTypeFramesElem struct {
	// BestEffortTimestamp corresponds to the JSON schema field
	// "best_effort_timestamp".
	BestEffortTimestamp *int `json:"best_effort_timestamp,omitempty,omitzero" yaml:"best_effort_timestamp,omitempty" mapstructure:"best_effort_timestamp,omitempty"`

	// BestEffortTimestampTime corresponds to the JSON schema field
	// "best_effort_timestamp_time".
	BestEffortTimestampTime *float64 `json:"best_effort_timestamp_time,omitempty,omitzero" yaml:"best_effort_timestamp_time,omitempty" mapstructure:"best_effort_timestamp_time,omitempty"`

	// ChannelLayout corresponds to the JSON schema field "channel_layout".
	ChannelLayout *string `json:"channel_layout,omitempty,omitzero" yaml:"channel_layout,omitempty" mapstructure:"channel_layout,omitempty"`

	// Channels corresponds to the JSON schema field "channels".
	Channels *int `json:"channels,omitempty,omitzero" yaml:"channels,omitempty" mapstructure:"channels,omitempty"`

	// ChromaLocation corresponds to the JSON schema field "chroma_location".
	ChromaLocation *string `json:"chroma_location,omitempty,omitzero" yaml:"chroma_location,omitempty" mapstructure:"chroma_location,omitempty"`

	// ColorPrimaries corresponds to the JSON schema field "color_primaries".
	ColorPrimaries *string `json:"color_primaries,omitempty,omitzero" yaml:"color_primaries,omitempty" mapstructure:"color_primaries,omitempty"`

	// ColorRange corresponds to the JSON schema field "color_range".
	ColorRange *string `json:"color_range,omitempty,omitzero" yaml:"color_range,omitempty" mapstructure:"color_range,omitempty"`

	// ColorSpace corresponds to the JSON schema field "color_space".
	ColorSpace *string `json:"color_space,omitempty,omitzero" yaml:"color_space,omitempty" mapstructure:"color_space,omitempty"`

	// ColorTransfer corresponds to the JSON schema field "color_transfer".
	ColorTransfer *string `json:"color_transfer,omitempty,omitzero" yaml:"color_transfer,omitempty" mapstructure:"color_transfer,omitempty"`

	// CropBottom corresponds to the JSON schema field "crop_bottom".
	CropBottom *int `json:"crop_bottom,omitempty,omitzero" yaml:"crop_bottom,omitempty" mapstructure:"crop_bottom,omitempty"`

	// CropLeft corresponds to the JSON schema field "crop_left".
	CropLeft *int `json:"crop_left,omitempty,omitzero" yaml:"crop_left,omitempty" mapstructure:"crop_left,omitempty"`

	// CropRight corresponds to the JSON schema field "crop_right".
	CropRight *int `json:"crop_right,omitempty,omitzero" yaml:"crop_right,omitempty" mapstructure:"crop_right,omitempty"`

	// CropTop corresponds to the JSON schema field "crop_top".
	CropTop *int `json:"crop_top,omitempty,omitzero" yaml:"crop_top,omitempty" mapstructure:"crop_top,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *int `json:"duration,omitempty,omitzero" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// DurationTime corresponds to the JSON schema field "duration_time".
	DurationTime *float64 `json:"duration_time,omitempty,omitzero" yaml:"duration_time,omitempty" mapstructure:"duration_time,omitempty"`

	// EndDisplayTime corresponds to the JSON schema field "end_display_time".
	EndDisplayTime *int `json:"end_display_time,omitempty,omitzero" yaml:"end_display_time,omitempty" mapstructure:"end_display_time,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format *int `json:"format,omitempty,omitzero" yaml:"format,omitempty" mapstructure:"format,omitempty"`

	// Height corresponds to the JSON schema field "height".
	Height *int `json:"height,omitempty,omitzero" yaml:"height,omitempty" mapstructure:"height,omitempty"`

	// InterlacedFrame corresponds to the JSON schema field "interlaced_frame".
	InterlacedFrame *int `json:"interlaced_frame,omitempty,omitzero" yaml:"interlaced_frame,omitempty" mapstructure:"interlaced_frame,omitempty"`

	// KeyFrame corresponds to the JSON schema field "key_frame".
	KeyFrame *int `json:"key_frame,omitempty,omitzero" yaml:"key_frame,omitempty" mapstructure:"key_frame,omitempty"`

	// Logs corresponds to the JSON schema field "logs".
	Logs *LogsType `json:"logs,omitempty,omitzero" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType string `json:"media_type" yaml:"media_type" mapstructure:"media_type"`

	// NbSamples corresponds to the JSON schema field "nb_samples".
	NbSamples *int `json:"nb_samples,omitempty,omitzero" yaml:"nb_samples,omitempty" mapstructure:"nb_samples,omitempty"`

	// NumRects corresponds to the JSON schema field "num_rects".
	NumRects *int `json:"num_rects,omitempty,omitzero" yaml:"num_rects,omitempty" mapstructure:"num_rects,omitempty"`

	// PictType corresponds to the JSON schema field "pict_type".
	PictType *string `json:"pict_type,omitempty,omitzero" yaml:"pict_type,omitempty" mapstructure:"pict_type,omitempty"`

	// PixFmt corresponds to the JSON schema field "pix_fmt".
	PixFmt *string `json:"pix_fmt,omitempty,omitzero" yaml:"pix_fmt,omitempty" mapstructure:"pix_fmt,omitempty"`

	// PktDts corresponds to the JSON schema field "pkt_dts".
	PktDts *int `json:"pkt_dts,omitempty,omitzero" yaml:"pkt_dts,omitempty" mapstructure:"pkt_dts,omitempty"`

	// PktDtsTime corresponds to the JSON schema field "pkt_dts_time".
	PktDtsTime *float64 `json:"pkt_dts_time,omitempty,omitzero" yaml:"pkt_dts_time,omitempty" mapstructure:"pkt_dts_time,omitempty"`

	// PktPos corresponds to the JSON schema field "pkt_pos".
	PktPos *int `json:"pkt_pos,omitempty,omitzero" yaml:"pkt_pos,omitempty" mapstructure:"pkt_pos,omitempty"`

	// PktSize corresponds to the JSON schema field "pkt_size".
	PktSize *int `json:"pkt_size,omitempty,omitzero" yaml:"pkt_size,omitempty" mapstructure:"pkt_size,omitempty"`

	// Pts corresponds to the JSON schema field "pts".
	Pts *int `json:"pts,omitempty,omitzero" yaml:"pts,omitempty" mapstructure:"pts,omitempty"`

	// PtsTime corresponds to the JSON schema field "pts_time".
	PtsTime *float64 `json:"pts_time,omitempty,omitzero" yaml:"pts_time,omitempty" mapstructure:"pts_time,omitempty"`

	// RepeatPict corresponds to the JSON schema field "repeat_pict".
	RepeatPict *int `json:"repeat_pict,omitempty,omitzero" yaml:"repeat_pict,omitempty" mapstructure:"repeat_pict,omitempty"`

	// SampleAspectRatio corresponds to the JSON schema field "sample_aspect_ratio".
	SampleAspectRatio *string `json:"sample_aspect_ratio,omitempty,omitzero" yaml:"sample_aspect_ratio,omitempty" mapstructure:"sample_aspect_ratio,omitempty"`

	// SampleFmt corresponds to the JSON schema field "sample_fmt".
	SampleFmt *string `json:"sample_fmt,omitempty,omitzero" yaml:"sample_fmt,omitempty" mapstructure:"sample_fmt,omitempty"`

	// SideDataList corresponds to the JSON schema field "side_data_list".
	SideDataList *FrameSideDataListType `json:"side_data_list,omitempty,omitzero" yaml:"side_data_list,omitempty" mapstructure:"side_data_list,omitempty"`

	// StartDisplayTime corresponds to the JSON schema field "start_display_time".
	StartDisplayTime *int `json:"start_display_time,omitempty,omitzero" yaml:"start_display_time,omitempty" mapstructure:"start_display_time,omitempty"`

	// StreamIndex corresponds to the JSON schema field "stream_index".
	StreamIndex *int `json:"stream_index,omitempty,omitzero" yaml:"stream_index,omitempty" mapstructure:"stream_index,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TopFieldFirst corresponds to the JSON schema field "top_field_first".
	TopFieldFirst *int `json:"top_field_first,omitempty,omitzero" yaml:"top_field_first,omitempty" mapstructure:"top_field_first,omitempty"`

	// Width corresponds to the JSON schema field "width".
	Width *int `json:"width,omitempty,omitzero" yaml:"width,omitempty" mapstructure:"width,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FfprobeTypeFramesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var ffprobeTypeFramesElem_0 FfprobeTypeFramesElem_0
	var ffprobeTypeFramesElem_1 FfprobeTypeFramesElem_1
	var errs []error
	if err := ffprobeTypeFramesElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := ffprobeTypeFramesElem_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 2 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain FfprobeTypeFramesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FfprobeTypeFramesElem(plain)
	return nil
}

type FfprobeTypePacketsAndFramesElem struct {
	// BestEffortTimestamp corresponds to the JSON schema field
	// "best_effort_timestamp".
	BestEffortTimestamp *int `json:"best_effort_timestamp,omitempty,omitzero" yaml:"best_effort_timestamp,omitempty" mapstructure:"best_effort_timestamp,omitempty"`

	// BestEffortTimestampTime corresponds to the JSON schema field
	// "best_effort_timestamp_time".
	BestEffortTimestampTime *float64 `json:"best_effort_timestamp_time,omitempty,omitzero" yaml:"best_effort_timestamp_time,omitempty" mapstructure:"best_effort_timestamp_time,omitempty"`

	// ChannelLayout corresponds to the JSON schema field "channel_layout".
	ChannelLayout *string `json:"channel_layout,omitempty,omitzero" yaml:"channel_layout,omitempty" mapstructure:"channel_layout,omitempty"`

	// Channels corresponds to the JSON schema field "channels".
	Channels *int `json:"channels,omitempty,omitzero" yaml:"channels,omitempty" mapstructure:"channels,omitempty"`

	// ChromaLocation corresponds to the JSON schema field "chroma_location".
	ChromaLocation *string `json:"chroma_location,omitempty,omitzero" yaml:"chroma_location,omitempty" mapstructure:"chroma_location,omitempty"`

	// CodecType corresponds to the JSON schema field "codec_type".
	CodecType *string `json:"codec_type,omitempty,omitzero" yaml:"codec_type,omitempty" mapstructure:"codec_type,omitempty"`

	// ColorPrimaries corresponds to the JSON schema field "color_primaries".
	ColorPrimaries *string `json:"color_primaries,omitempty,omitzero" yaml:"color_primaries,omitempty" mapstructure:"color_primaries,omitempty"`

	// ColorRange corresponds to the JSON schema field "color_range".
	ColorRange *string `json:"color_range,omitempty,omitzero" yaml:"color_range,omitempty" mapstructure:"color_range,omitempty"`

	// ColorSpace corresponds to the JSON schema field "color_space".
	ColorSpace *string `json:"color_space,omitempty,omitzero" yaml:"color_space,omitempty" mapstructure:"color_space,omitempty"`

	// ColorTransfer corresponds to the JSON schema field "color_transfer".
	ColorTransfer *string `json:"color_transfer,omitempty,omitzero" yaml:"color_transfer,omitempty" mapstructure:"color_transfer,omitempty"`

	// CropBottom corresponds to the JSON schema field "crop_bottom".
	CropBottom *int `json:"crop_bottom,omitempty,omitzero" yaml:"crop_bottom,omitempty" mapstructure:"crop_bottom,omitempty"`

	// CropLeft corresponds to the JSON schema field "crop_left".
	CropLeft *int `json:"crop_left,omitempty,omitzero" yaml:"crop_left,omitempty" mapstructure:"crop_left,omitempty"`

	// CropRight corresponds to the JSON schema field "crop_right".
	CropRight *int `json:"crop_right,omitempty,omitzero" yaml:"crop_right,omitempty" mapstructure:"crop_right,omitempty"`

	// CropTop corresponds to the JSON schema field "crop_top".
	CropTop *int `json:"crop_top,omitempty,omitzero" yaml:"crop_top,omitempty" mapstructure:"crop_top,omitempty"`

	// Data corresponds to the JSON schema field "data".
	Data *string `json:"data,omitempty,omitzero" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// DataHash corresponds to the JSON schema field "data_hash".
	DataHash *string `json:"data_hash,omitempty,omitzero" yaml:"data_hash,omitempty" mapstructure:"data_hash,omitempty"`

	// Dts corresponds to the JSON schema field "dts".
	Dts *int `json:"dts,omitempty,omitzero" yaml:"dts,omitempty" mapstructure:"dts,omitempty"`

	// DtsTime corresponds to the JSON schema field "dts_time".
	DtsTime *string `json:"dts_time,omitempty,omitzero" yaml:"dts_time,omitempty" mapstructure:"dts_time,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *int `json:"duration,omitempty,omitzero" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// DurationTime corresponds to the JSON schema field "duration_time".
	DurationTime *string `json:"duration_time,omitempty,omitzero" yaml:"duration_time,omitempty" mapstructure:"duration_time,omitempty"`

	// EndDisplayTime corresponds to the JSON schema field "end_display_time".
	EndDisplayTime *int `json:"end_display_time,omitempty,omitzero" yaml:"end_display_time,omitempty" mapstructure:"end_display_time,omitempty"`

	// Flags corresponds to the JSON schema field "flags".
	Flags *string `json:"flags,omitempty,omitzero" yaml:"flags,omitempty" mapstructure:"flags,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format *int `json:"format,omitempty,omitzero" yaml:"format,omitempty" mapstructure:"format,omitempty"`

	// Height corresponds to the JSON schema field "height".
	Height *int `json:"height,omitempty,omitzero" yaml:"height,omitempty" mapstructure:"height,omitempty"`

	// InterlacedFrame corresponds to the JSON schema field "interlaced_frame".
	InterlacedFrame *int `json:"interlaced_frame,omitempty,omitzero" yaml:"interlaced_frame,omitempty" mapstructure:"interlaced_frame,omitempty"`

	// KeyFrame corresponds to the JSON schema field "key_frame".
	KeyFrame *int `json:"key_frame,omitempty,omitzero" yaml:"key_frame,omitempty" mapstructure:"key_frame,omitempty"`

	// Logs corresponds to the JSON schema field "logs".
	Logs *LogsType `json:"logs,omitempty,omitzero" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType *string `json:"media_type,omitempty,omitzero" yaml:"media_type,omitempty" mapstructure:"media_type,omitempty"`

	// NbSamples corresponds to the JSON schema field "nb_samples".
	NbSamples *int `json:"nb_samples,omitempty,omitzero" yaml:"nb_samples,omitempty" mapstructure:"nb_samples,omitempty"`

	// NumRects corresponds to the JSON schema field "num_rects".
	NumRects *int `json:"num_rects,omitempty,omitzero" yaml:"num_rects,omitempty" mapstructure:"num_rects,omitempty"`

	// PictType corresponds to the JSON schema field "pict_type".
	PictType *string `json:"pict_type,omitempty,omitzero" yaml:"pict_type,omitempty" mapstructure:"pict_type,omitempty"`

	// PixFmt corresponds to the JSON schema field "pix_fmt".
	PixFmt *string `json:"pix_fmt,omitempty,omitzero" yaml:"pix_fmt,omitempty" mapstructure:"pix_fmt,omitempty"`

	// PktDts corresponds to the JSON schema field "pkt_dts".
	PktDts *int `json:"pkt_dts,omitempty,omitzero" yaml:"pkt_dts,omitempty" mapstructure:"pkt_dts,omitempty"`

	// PktDtsTime corresponds to the JSON schema field "pkt_dts_time".
	PktDtsTime *float64 `json:"pkt_dts_time,omitempty,omitzero" yaml:"pkt_dts_time,omitempty" mapstructure:"pkt_dts_time,omitempty"`

	// PktPos corresponds to the JSON schema field "pkt_pos".
	PktPos *int `json:"pkt_pos,omitempty,omitzero" yaml:"pkt_pos,omitempty" mapstructure:"pkt_pos,omitempty"`

	// PktSize corresponds to the JSON schema field "pkt_size".
	PktSize *int `json:"pkt_size,omitempty,omitzero" yaml:"pkt_size,omitempty" mapstructure:"pkt_size,omitempty"`

	// Pos corresponds to the JSON schema field "pos".
	Pos *int `json:"pos,omitempty,omitzero" yaml:"pos,omitempty" mapstructure:"pos,omitempty"`

	// Pts corresponds to the JSON schema field "pts".
	Pts *int `json:"pts,omitempty,omitzero" yaml:"pts,omitempty" mapstructure:"pts,omitempty"`

	// PtsTime corresponds to the JSON schema field "pts_time".
	PtsTime *string `json:"pts_time,omitempty,omitzero" yaml:"pts_time,omitempty" mapstructure:"pts_time,omitempty"`

	// RepeatPict corresponds to the JSON schema field "repeat_pict".
	RepeatPict *int `json:"repeat_pict,omitempty,omitzero" yaml:"repeat_pict,omitempty" mapstructure:"repeat_pict,omitempty"`

	// SampleAspectRatio corresponds to the JSON schema field "sample_aspect_ratio".
	SampleAspectRatio *string `json:"sample_aspect_ratio,omitempty,omitzero" yaml:"sample_aspect_ratio,omitempty" mapstructure:"sample_aspect_ratio,omitempty"`

	// SampleFmt corresponds to the JSON schema field "sample_fmt".
	SampleFmt *string `json:"sample_fmt,omitempty,omitzero" yaml:"sample_fmt,omitempty" mapstructure:"sample_fmt,omitempty"`

	// SideDataList corresponds to the JSON schema field "side_data_list".
	SideDataList *PacketSideDataListType `json:"side_data_list,omitempty,omitzero" yaml:"side_data_list,omitempty" mapstructure:"side_data_list,omitempty"`

	// Size corresponds to the JSON schema field "size".
	Size *int `json:"size,omitempty,omitzero" yaml:"size,omitempty" mapstructure:"size,omitempty"`

	// StartDisplayTime corresponds to the JSON schema field "start_display_time".
	StartDisplayTime *int `json:"start_display_time,omitempty,omitzero" yaml:"start_display_time,omitempty" mapstructure:"start_display_time,omitempty"`

	// StreamIndex corresponds to the JSON schema field "stream_index".
	StreamIndex *int `json:"stream_index,omitempty,omitzero" yaml:"stream_index,omitempty" mapstructure:"stream_index,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TopFieldFirst corresponds to the JSON schema field "top_field_first".
	TopFieldFirst *int `json:"top_field_first,omitempty,omitzero" yaml:"top_field_first,omitempty" mapstructure:"top_field_first,omitempty"`

	// Width corresponds to the JSON schema field "width".
	Width *int `json:"width,omitempty,omitzero" yaml:"width,omitempty" mapstructure:"width,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FfprobeTypePacketsAndFramesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var ffprobeTypePacketsAndFramesElem_0 FfprobeTypePacketsAndFramesElem_0
	var ffprobeTypePacketsAndFramesElem_1 FfprobeTypePacketsAndFramesElem_1
	var ffprobeTypePacketsAndFramesElem_2 FfprobeTypePacketsAndFramesElem_2
	var errs []error
	if err := ffprobeTypePacketsAndFramesElem_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := ffprobeTypePacketsAndFramesElem_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := ffprobeTypePacketsAndFramesElem_2.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 3 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain FfprobeTypePacketsAndFramesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FfprobeTypePacketsAndFramesElem(plain)
	return nil
}

type FormatType struct {
	// BitRate corresponds to the JSON schema field "bit_rate".
	BitRate *string `json:"bit_rate,omitempty,omitzero" yaml:"bit_rate,omitempty" mapstructure:"bit_rate,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *string `json:"duration,omitempty,omitzero" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// Filename corresponds to the JSON schema field "filename".
	Filename string `json:"filename" yaml:"filename" mapstructure:"filename"`

	// FormatLongName corresponds to the JSON schema field "format_long_name".
	FormatLongName *string `json:"format_long_name,omitempty,omitzero" yaml:"format_long_name,omitempty" mapstructure:"format_long_name,omitempty"`

	// FormatName corresponds to the JSON schema field "format_name".
	FormatName string `json:"format_name" yaml:"format_name" mapstructure:"format_name"`

	// NbPrograms corresponds to the JSON schema field "nb_programs".
	NbPrograms int `json:"nb_programs" yaml:"nb_programs" mapstructure:"nb_programs"`

	// NbStreamGroups corresponds to the JSON schema field "nb_stream_groups".
	NbStreamGroups int `json:"nb_stream_groups" yaml:"nb_stream_groups" mapstructure:"nb_stream_groups"`

	// NbStreams corresponds to the JSON schema field "nb_streams".
	NbStreams int `json:"nb_streams" yaml:"nb_streams" mapstructure:"nb_streams"`

	// ProbeScore corresponds to the JSON schema field "probe_score".
	ProbeScore *int `json:"probe_score,omitempty,omitzero" yaml:"probe_score,omitempty" mapstructure:"probe_score,omitempty"`

	// Size corresponds to the JSON schema field "size".
	Size *string `json:"size,omitempty,omitzero" yaml:"size,omitempty" mapstructure:"size,omitempty"`

	// StartTime corresponds to the JSON schema field "start_time".
	StartTime *string `json:"start_time,omitempty,omitzero" yaml:"start_time,omitempty" mapstructure:"start_time,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FormatType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["filename"]; raw != nil && !ok {
		return fmt.Errorf("field filename in FormatType: required")
	}
	if _, ok := raw["format_name"]; raw != nil && !ok {
		return fmt.Errorf("field format_name in FormatType: required")
	}
	if _, ok := raw["nb_programs"]; raw != nil && !ok {
		return fmt.Errorf("field nb_programs in FormatType: required")
	}
	if _, ok := raw["nb_stream_groups"]; raw != nil && !ok {
		return fmt.Errorf("field nb_stream_groups in FormatType: required")
	}
	if _, ok := raw["nb_streams"]; raw != nil && !ok {
		return fmt.Errorf("field nb_streams in FormatType: required")
	}
	type Plain FormatType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FormatType(plain)
	return nil
}

type FrameSideDataComponentList struct {
	// Component corresponds to the JSON schema field "component".
	Component []FrameSideDataComponentType `json:"component,omitempty,omitzero" yaml:"component,omitempty" mapstructure:"component,omitempty"`
}

type FrameSideDataComponentType struct {
	// Pieces corresponds to the JSON schema field "pieces".
	Pieces *FrameSideDataPieceList `json:"pieces,omitempty,omitzero" yaml:"pieces,omitempty" mapstructure:"pieces,omitempty"`

	// SideDatum corresponds to the JSON schema field "side_datum".
	SideDatum []FrameSideDatumType `json:"side_datum,omitempty,omitzero" yaml:"side_datum,omitempty" mapstructure:"side_datum,omitempty"`
}

type FrameSideDataListType struct {
	// SideData corresponds to the JSON schema field "side_data".
	SideData []FrameSideDataType `json:"side_data" yaml:"side_data" mapstructure:"side_data"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FrameSideDataListType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["side_data"]; raw != nil && !ok {
		return fmt.Errorf("field side_data in FrameSideDataListType: required")
	}
	type Plain FrameSideDataListType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SideData != nil && len(plain.SideData) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "side_data", 1)
	}
	*j = FrameSideDataListType(plain)
	return nil
}

type FrameSideDataPieceList struct {
	// Piece corresponds to the JSON schema field "piece".
	Piece []FrameSideDataPieceType `json:"piece,omitempty,omitzero" yaml:"piece,omitempty" mapstructure:"piece,omitempty"`
}

type FrameSideDataPieceType struct {
	// SideDatum corresponds to the JSON schema field "side_datum".
	SideDatum []FrameSideDatumType `json:"side_datum,omitempty,omitzero" yaml:"side_datum,omitempty" mapstructure:"side_datum,omitempty"`
}

type FrameSideDataTimecodeList struct {
	// Timecode corresponds to the JSON schema field "timecode".
	Timecode []FrameSideDataTimecodeType `json:"timecode,omitempty,omitzero" yaml:"timecode,omitempty" mapstructure:"timecode,omitempty"`
}

type FfprobeTypeFramesElem_0 = FrameType

// UnmarshalJSON implements json.Unmarshaler.
func (j *StreamType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["avg_frame_rate"]; raw != nil && !ok {
		return fmt.Errorf("field avg_frame_rate in StreamType: required")
	}
	if _, ok := raw["codec_tag"]; raw != nil && !ok {
		return fmt.Errorf("field codec_tag in StreamType: required")
	}
	if _, ok := raw["codec_tag_string"]; raw != nil && !ok {
		return fmt.Errorf("field codec_tag_string in StreamType: required")
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in StreamType: required")
	}
	if _, ok := raw["r_frame_rate"]; raw != nil && !ok {
		return fmt.Errorf("field r_frame_rate in StreamType: required")
	}
	if _, ok := raw["time_base"]; raw != nil && !ok {
		return fmt.Errorf("field time_base in StreamType: required")
	}
	type Plain StreamType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StreamType(plain)
	return nil
}

type StreamsType struct {
	// Stream corresponds to the JSON schema field "stream".
	Stream []StreamType `json:"stream,omitempty,omitzero" yaml:"stream,omitempty" mapstructure:"stream,omitempty"`
}

type StreamGroupType struct {
	// Components corresponds to the JSON schema field "components".
	Components *StreamGroupComponentList `json:"components,omitempty,omitzero" yaml:"components,omitempty" mapstructure:"components,omitempty"`

	// Disposition corresponds to the JSON schema field "disposition".
	Disposition *StreamDispositionType `json:"disposition,omitempty,omitzero" yaml:"disposition,omitempty" mapstructure:"disposition,omitempty"`

	// Index corresponds to the JSON schema field "index".
	Index int `json:"index" yaml:"index" mapstructure:"index"`

	// NbStreams corresponds to the JSON schema field "nb_streams".
	NbStreams int `json:"nb_streams" yaml:"nb_streams" mapstructure:"nb_streams"`

	// Streams corresponds to the JSON schema field "streams".
	Streams *StreamsType `json:"streams,omitempty,omitzero" yaml:"streams,omitempty" mapstructure:"streams,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StreamGroupType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in StreamGroupType: required")
	}
	if _, ok := raw["nb_streams"]; raw != nil && !ok {
		return fmt.Errorf("field nb_streams in StreamGroupType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in StreamGroupType: required")
	}
	type Plain StreamGroupType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StreamGroupType(plain)
	return nil
}

type StreamGroupsType struct {
	// StreamGroup corresponds to the JSON schema field "stream_group".
	StreamGroup []StreamGroupType `json:"stream_group,omitempty,omitzero" yaml:"stream_group,omitempty" mapstructure:"stream_group,omitempty"`
}

type TagsType map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *PacketSideDataListType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["side_data"]; raw != nil && !ok {
		return fmt.Errorf("field side_data in PacketSideDataListType: required")
	}
	type Plain PacketSideDataListType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SideData != nil && len(plain.SideData) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "side_data", 1)
	}
	*j = PacketSideDataListType(plain)
	return nil
}

type PacketSideDataListType struct {
	// SideData corresponds to the JSON schema field "side_data".
	SideData []PacketSideDataType `json:"side_data" yaml:"side_data" mapstructure:"side_data"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PacketSideDataType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["side_datum"]; raw != nil && !ok {
		return fmt.Errorf("field side_datum in PacketSideDataType: required")
	}
	type Plain PacketSideDataType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.SideDatum != nil && len(plain.SideDatum) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "side_datum", 1)
	}
	*j = PacketSideDataType(plain)
	return nil
}

type PacketSideDataType struct {
	// SideDatum corresponds to the JSON schema field "side_datum".
	SideDatum []PacketSideDatumType `json:"side_datum" yaml:"side_datum" mapstructure:"side_datum"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type PacketSideDatumType struct {
	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty,omitzero" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value *string `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StreamDispositionType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["attached_pic"]; raw != nil && !ok {
		return fmt.Errorf("field attached_pic in StreamDispositionType: required")
	}
	if _, ok := raw["captions"]; raw != nil && !ok {
		return fmt.Errorf("field captions in StreamDispositionType: required")
	}
	if _, ok := raw["clean_effects"]; raw != nil && !ok {
		return fmt.Errorf("field clean_effects in StreamDispositionType: required")
	}
	if _, ok := raw["comment"]; raw != nil && !ok {
		return fmt.Errorf("field comment in StreamDispositionType: required")
	}
	if _, ok := raw["default"]; raw != nil && !ok {
		return fmt.Errorf("field default in StreamDispositionType: required")
	}
	if _, ok := raw["dependent"]; raw != nil && !ok {
		return fmt.Errorf("field dependent in StreamDispositionType: required")
	}
	if _, ok := raw["descriptions"]; raw != nil && !ok {
		return fmt.Errorf("field descriptions in StreamDispositionType: required")
	}
	if _, ok := raw["dub"]; raw != nil && !ok {
		return fmt.Errorf("field dub in StreamDispositionType: required")
	}
	if _, ok := raw["forced"]; raw != nil && !ok {
		return fmt.Errorf("field forced in StreamDispositionType: required")
	}
	if _, ok := raw["hearing_impaired"]; raw != nil && !ok {
		return fmt.Errorf("field hearing_impaired in StreamDispositionType: required")
	}
	if _, ok := raw["karaoke"]; raw != nil && !ok {
		return fmt.Errorf("field karaoke in StreamDispositionType: required")
	}
	if _, ok := raw["lyrics"]; raw != nil && !ok {
		return fmt.Errorf("field lyrics in StreamDispositionType: required")
	}
	if _, ok := raw["metadata"]; raw != nil && !ok {
		return fmt.Errorf("field metadata in StreamDispositionType: required")
	}
	if _, ok := raw["multilayer"]; raw != nil && !ok {
		return fmt.Errorf("field multilayer in StreamDispositionType: required")
	}
	if _, ok := raw["non_diegetic"]; raw != nil && !ok {
		return fmt.Errorf("field non_diegetic in StreamDispositionType: required")
	}
	if _, ok := raw["original"]; raw != nil && !ok {
		return fmt.Errorf("field original in StreamDispositionType: required")
	}
	if _, ok := raw["still_image"]; raw != nil && !ok {
		return fmt.Errorf("field still_image in StreamDispositionType: required")
	}
	if _, ok := raw["timed_thumbnails"]; raw != nil && !ok {
		return fmt.Errorf("field timed_thumbnails in StreamDispositionType: required")
	}
	if _, ok := raw["visual_impaired"]; raw != nil && !ok {
		return fmt.Errorf("field visual_impaired in StreamDispositionType: required")
	}
	type Plain StreamDispositionType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = StreamDispositionType(plain)
	return nil
}

type LogType struct {
	// Category corresponds to the JSON schema field "category".
	Category *int `json:"category,omitempty,omitzero" yaml:"category,omitempty" mapstructure:"category,omitempty"`

	// Context corresponds to the JSON schema field "context".
	Context *string `json:"context,omitempty,omitzero" yaml:"context,omitempty" mapstructure:"context,omitempty"`

	// Level corresponds to the JSON schema field "level".
	Level *int `json:"level,omitempty,omitzero" yaml:"level,omitempty" mapstructure:"level,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// ParentCategory corresponds to the JSON schema field "parent_category".
	ParentCategory *int `json:"parent_category,omitempty,omitzero" yaml:"parent_category,omitempty" mapstructure:"parent_category,omitempty"`

	// ParentContext corresponds to the JSON schema field "parent_context".
	ParentContext *string `json:"parent_context,omitempty,omitzero" yaml:"parent_context,omitempty" mapstructure:"parent_context,omitempty"`
}

type LogsType struct {
	// Log corresponds to the JSON schema field "log".
	Log []LogType `json:"log" yaml:"log" mapstructure:"log"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LogsType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["log"]; raw != nil && !ok {
		return fmt.Errorf("field log in LogsType: required")
	}
	type Plain LogsType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Log != nil && len(plain.Log) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "log", 1)
	}
	*j = LogsType(plain)
	return nil
}

type FrameSideDatumType struct {
	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty,omitzero" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value *string `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

type StreamDispositionType struct {
	// AttachedPic corresponds to the JSON schema field "attached_pic".
	AttachedPic int `json:"attached_pic" yaml:"attached_pic" mapstructure:"attached_pic"`

	// Captions corresponds to the JSON schema field "captions".
	Captions int `json:"captions" yaml:"captions" mapstructure:"captions"`

	// CleanEffects corresponds to the JSON schema field "clean_effects".
	CleanEffects int `json:"clean_effects" yaml:"clean_effects" mapstructure:"clean_effects"`

	// Comment corresponds to the JSON schema field "comment".
	Comment int `json:"comment" yaml:"comment" mapstructure:"comment"`

	// Default corresponds to the JSON schema field "default".
	Default int `json:"default" yaml:"default" mapstructure:"default"`

	// Dependent corresponds to the JSON schema field "dependent".
	Dependent int `json:"dependent" yaml:"dependent" mapstructure:"dependent"`

	// Descriptions corresponds to the JSON schema field "descriptions".
	Descriptions int `json:"descriptions" yaml:"descriptions" mapstructure:"descriptions"`

	// Dub corresponds to the JSON schema field "dub".
	Dub int `json:"dub" yaml:"dub" mapstructure:"dub"`

	// Forced corresponds to the JSON schema field "forced".
	Forced int `json:"forced" yaml:"forced" mapstructure:"forced"`

	// HearingImpaired corresponds to the JSON schema field "hearing_impaired".
	HearingImpaired int `json:"hearing_impaired" yaml:"hearing_impaired" mapstructure:"hearing_impaired"`

	// Karaoke corresponds to the JSON schema field "karaoke".
	Karaoke int `json:"karaoke" yaml:"karaoke" mapstructure:"karaoke"`

	// Lyrics corresponds to the JSON schema field "lyrics".
	Lyrics int `json:"lyrics" yaml:"lyrics" mapstructure:"lyrics"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata int `json:"metadata" yaml:"metadata" mapstructure:"metadata"`

	// Multilayer corresponds to the JSON schema field "multilayer".
	Multilayer int `json:"multilayer" yaml:"multilayer" mapstructure:"multilayer"`

	// NonDiegetic corresponds to the JSON schema field "non_diegetic".
	NonDiegetic int `json:"non_diegetic" yaml:"non_diegetic" mapstructure:"non_diegetic"`

	// Original corresponds to the JSON schema field "original".
	Original int `json:"original" yaml:"original" mapstructure:"original"`

	// StillImage corresponds to the JSON schema field "still_image".
	StillImage int `json:"still_image" yaml:"still_image" mapstructure:"still_image"`

	// TimedThumbnails corresponds to the JSON schema field "timed_thumbnails".
	TimedThumbnails int `json:"timed_thumbnails" yaml:"timed_thumbnails" mapstructure:"timed_thumbnails"`

	// VisualImpaired corresponds to the JSON schema field "visual_impaired".
	VisualImpaired int `json:"visual_impaired" yaml:"visual_impaired" mapstructure:"visual_impaired"`
}

type StreamGroupComponentList struct {
	// Component corresponds to the JSON schema field "component".
	Component []StreamGroupComponentType `json:"component,omitempty,omitzero" yaml:"component,omitempty" mapstructure:"component,omitempty"`
}

type StreamGroupComponentType struct {
	// ComponentEntry corresponds to the JSON schema field "component_entry".
	ComponentEntry []StreamGroupEntryType `json:"component_entry,omitempty,omitzero" yaml:"component_entry,omitempty" mapstructure:"component_entry,omitempty"`

	// Subcomponents corresponds to the JSON schema field "subcomponents".
	Subcomponents *StreamGroupSubComponentList `json:"subcomponents,omitempty,omitzero" yaml:"subcomponents,omitempty" mapstructure:"subcomponents,omitempty"`
}

type StreamGroupSubComponentList struct {
	// Subcomponent corresponds to the JSON schema field "subcomponent".
	Subcomponent []StreamGroupSubComponentType `json:"subcomponent,omitempty,omitzero" yaml:"subcomponent,omitempty" mapstructure:"subcomponent,omitempty"`
}

type FrameSideDataTimecodeType struct {
	// Value corresponds to the JSON schema field "value".
	Value *string `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

type StreamGroupEntryType struct {
	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty,omitzero" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Value corresponds to the JSON schema field "value".
	Value *string `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

type FrameSideDataType struct {
	// Components corresponds to the JSON schema field "components".
	Components *FrameSideDataComponentList `json:"components,omitempty,omitzero" yaml:"components,omitempty" mapstructure:"components,omitempty"`

	// SideDataSize corresponds to the JSON schema field "side_data_size".
	SideDataSize *int `json:"side_data_size,omitempty,omitzero" yaml:"side_data_size,omitempty" mapstructure:"side_data_size,omitempty"`

	// SideDataType corresponds to the JSON schema field "side_data_type".
	SideDataType *string `json:"side_data_type,omitempty,omitzero" yaml:"side_data_type,omitempty" mapstructure:"side_data_type,omitempty"`

	// SideDatum corresponds to the JSON schema field "side_datum".
	SideDatum []FrameSideDatumType `json:"side_datum,omitempty,omitzero" yaml:"side_datum,omitempty" mapstructure:"side_datum,omitempty"`

	// Timecode corresponds to the JSON schema field "timecode".
	Timecode *string `json:"timecode,omitempty,omitzero" yaml:"timecode,omitempty" mapstructure:"timecode,omitempty"`

	// Timecodes corresponds to the JSON schema field "timecodes".
	Timecodes *FrameSideDataTimecodeList `json:"timecodes,omitempty,omitzero" yaml:"timecodes,omitempty" mapstructure:"timecodes,omitempty"`
}

type StreamGroupSubComponentType struct {
	// Pieces corresponds to the JSON schema field "pieces".
	Pieces *StreamGroupPieceList `json:"pieces,omitempty,omitzero" yaml:"pieces,omitempty" mapstructure:"pieces,omitempty"`

	// SubcomponentEntry corresponds to the JSON schema field "subcomponent_entry".
	SubcomponentEntry []StreamGroupEntryType `json:"subcomponent_entry,omitempty,omitzero" yaml:"subcomponent_entry,omitempty" mapstructure:"subcomponent_entry,omitempty"`
}

type StreamGroupPieceList struct {
	// Piece corresponds to the JSON schema field "piece".
	Piece []StreamGroupPieceType `json:"piece,omitempty,omitzero" yaml:"piece,omitempty" mapstructure:"piece,omitempty"`
}

type FrameType struct {
	// BestEffortTimestamp corresponds to the JSON schema field
	// "best_effort_timestamp".
	BestEffortTimestamp *int `json:"best_effort_timestamp,omitempty,omitzero" yaml:"best_effort_timestamp,omitempty" mapstructure:"best_effort_timestamp,omitempty"`

	// BestEffortTimestampTime corresponds to the JSON schema field
	// "best_effort_timestamp_time".
	BestEffortTimestampTime *float64 `json:"best_effort_timestamp_time,omitempty,omitzero" yaml:"best_effort_timestamp_time,omitempty" mapstructure:"best_effort_timestamp_time,omitempty"`

	// ChannelLayout corresponds to the JSON schema field "channel_layout".
	ChannelLayout *string `json:"channel_layout,omitempty,omitzero" yaml:"channel_layout,omitempty" mapstructure:"channel_layout,omitempty"`

	// Channels corresponds to the JSON schema field "channels".
	Channels *int `json:"channels,omitempty,omitzero" yaml:"channels,omitempty" mapstructure:"channels,omitempty"`

	// ChromaLocation corresponds to the JSON schema field "chroma_location".
	ChromaLocation *string `json:"chroma_location,omitempty,omitzero" yaml:"chroma_location,omitempty" mapstructure:"chroma_location,omitempty"`

	// ColorPrimaries corresponds to the JSON schema field "color_primaries".
	ColorPrimaries *string `json:"color_primaries,omitempty,omitzero" yaml:"color_primaries,omitempty" mapstructure:"color_primaries,omitempty"`

	// ColorRange corresponds to the JSON schema field "color_range".
	ColorRange *string `json:"color_range,omitempty,omitzero" yaml:"color_range,omitempty" mapstructure:"color_range,omitempty"`

	// ColorSpace corresponds to the JSON schema field "color_space".
	ColorSpace *string `json:"color_space,omitempty,omitzero" yaml:"color_space,omitempty" mapstructure:"color_space,omitempty"`

	// ColorTransfer corresponds to the JSON schema field "color_transfer".
	ColorTransfer *string `json:"color_transfer,omitempty,omitzero" yaml:"color_transfer,omitempty" mapstructure:"color_transfer,omitempty"`

	// CropBottom corresponds to the JSON schema field "crop_bottom".
	CropBottom *int `json:"crop_bottom,omitempty,omitzero" yaml:"crop_bottom,omitempty" mapstructure:"crop_bottom,omitempty"`

	// CropLeft corresponds to the JSON schema field "crop_left".
	CropLeft *int `json:"crop_left,omitempty,omitzero" yaml:"crop_left,omitempty" mapstructure:"crop_left,omitempty"`

	// CropRight corresponds to the JSON schema field "crop_right".
	CropRight *int `json:"crop_right,omitempty,omitzero" yaml:"crop_right,omitempty" mapstructure:"crop_right,omitempty"`

	// CropTop corresponds to the JSON schema field "crop_top".
	CropTop *int `json:"crop_top,omitempty,omitzero" yaml:"crop_top,omitempty" mapstructure:"crop_top,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *int `json:"duration,omitempty,omitzero" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// DurationTime corresponds to the JSON schema field "duration_time".
	DurationTime *float64 `json:"duration_time,omitempty,omitzero" yaml:"duration_time,omitempty" mapstructure:"duration_time,omitempty"`

	// Height corresponds to the JSON schema field "height".
	Height *int `json:"height,omitempty,omitzero" yaml:"height,omitempty" mapstructure:"height,omitempty"`

	// InterlacedFrame corresponds to the JSON schema field "interlaced_frame".
	InterlacedFrame *int `json:"interlaced_frame,omitempty,omitzero" yaml:"interlaced_frame,omitempty" mapstructure:"interlaced_frame,omitempty"`

	// KeyFrame corresponds to the JSON schema field "key_frame".
	KeyFrame int `json:"key_frame" yaml:"key_frame" mapstructure:"key_frame"`

	// Logs corresponds to the JSON schema field "logs".
	Logs *LogsType `json:"logs,omitempty,omitzero" yaml:"logs,omitempty" mapstructure:"logs,omitempty"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType string `json:"media_type" yaml:"media_type" mapstructure:"media_type"`

	// NbSamples corresponds to the JSON schema field "nb_samples".
	NbSamples *int `json:"nb_samples,omitempty,omitzero" yaml:"nb_samples,omitempty" mapstructure:"nb_samples,omitempty"`

	// PictType corresponds to the JSON schema field "pict_type".
	PictType *string `json:"pict_type,omitempty,omitzero" yaml:"pict_type,omitempty" mapstructure:"pict_type,omitempty"`

	// PixFmt corresponds to the JSON schema field "pix_fmt".
	PixFmt *string `json:"pix_fmt,omitempty,omitzero" yaml:"pix_fmt,omitempty" mapstructure:"pix_fmt,omitempty"`

	// PktDts corresponds to the JSON schema field "pkt_dts".
	PktDts *int `json:"pkt_dts,omitempty,omitzero" yaml:"pkt_dts,omitempty" mapstructure:"pkt_dts,omitempty"`

	// PktDtsTime corresponds to the JSON schema field "pkt_dts_time".
	PktDtsTime *float64 `json:"pkt_dts_time,omitempty,omitzero" yaml:"pkt_dts_time,omitempty" mapstructure:"pkt_dts_time,omitempty"`

	// PktPos corresponds to the JSON schema field "pkt_pos".
	PktPos *int `json:"pkt_pos,omitempty,omitzero" yaml:"pkt_pos,omitempty" mapstructure:"pkt_pos,omitempty"`

	// PktSize corresponds to the JSON schema field "pkt_size".
	PktSize *int `json:"pkt_size,omitempty,omitzero" yaml:"pkt_size,omitempty" mapstructure:"pkt_size,omitempty"`

	// Pts corresponds to the JSON schema field "pts".
	Pts *int `json:"pts,omitempty,omitzero" yaml:"pts,omitempty" mapstructure:"pts,omitempty"`

	// PtsTime corresponds to the JSON schema field "pts_time".
	PtsTime *float64 `json:"pts_time,omitempty,omitzero" yaml:"pts_time,omitempty" mapstructure:"pts_time,omitempty"`

	// RepeatPict corresponds to the JSON schema field "repeat_pict".
	RepeatPict *int `json:"repeat_pict,omitempty,omitzero" yaml:"repeat_pict,omitempty" mapstructure:"repeat_pict,omitempty"`

	// SampleAspectRatio corresponds to the JSON schema field "sample_aspect_ratio".
	SampleAspectRatio *string `json:"sample_aspect_ratio,omitempty,omitzero" yaml:"sample_aspect_ratio,omitempty" mapstructure:"sample_aspect_ratio,omitempty"`

	// SampleFmt corresponds to the JSON schema field "sample_fmt".
	SampleFmt *string `json:"sample_fmt,omitempty,omitzero" yaml:"sample_fmt,omitempty" mapstructure:"sample_fmt,omitempty"`

	// SideDataList corresponds to the JSON schema field "side_data_list".
	SideDataList *FrameSideDataListType `json:"side_data_list,omitempty,omitzero" yaml:"side_data_list,omitempty" mapstructure:"side_data_list,omitempty"`

	// StreamIndex corresponds to the JSON schema field "stream_index".
	StreamIndex *int `json:"stream_index,omitempty,omitzero" yaml:"stream_index,omitempty" mapstructure:"stream_index,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TopFieldFirst corresponds to the JSON schema field "top_field_first".
	TopFieldFirst *int `json:"top_field_first,omitempty,omitzero" yaml:"top_field_first,omitempty" mapstructure:"top_field_first,omitempty"`

	// Width corresponds to the JSON schema field "width".
	Width *int `json:"width,omitempty,omitzero" yaml:"width,omitempty" mapstructure:"width,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FrameType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key_frame"]; raw != nil && !ok {
		return fmt.Errorf("field key_frame in FrameType: required")
	}
	if _, ok := raw["media_type"]; raw != nil && !ok {
		return fmt.Errorf("field media_type in FrameType: required")
	}
	type Plain FrameType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = FrameType(plain)
	return nil
}

type SubtitleType struct {
	// EndDisplayTime corresponds to the JSON schema field "end_display_time".
	EndDisplayTime *int `json:"end_display_time,omitempty,omitzero" yaml:"end_display_time,omitempty" mapstructure:"end_display_time,omitempty"`

	// Format corresponds to the JSON schema field "format".
	Format *int `json:"format,omitempty,omitzero" yaml:"format,omitempty" mapstructure:"format,omitempty"`

	// MediaType corresponds to the JSON schema field "media_type".
	MediaType string `json:"media_type" yaml:"media_type" mapstructure:"media_type"`

	// NumRects corresponds to the JSON schema field "num_rects".
	NumRects *int `json:"num_rects,omitempty,omitzero" yaml:"num_rects,omitempty" mapstructure:"num_rects,omitempty"`

	// Pts corresponds to the JSON schema field "pts".
	Pts *int `json:"pts,omitempty,omitzero" yaml:"pts,omitempty" mapstructure:"pts,omitempty"`

	// PtsTime corresponds to the JSON schema field "pts_time".
	PtsTime *float64 `json:"pts_time,omitempty,omitzero" yaml:"pts_time,omitempty" mapstructure:"pts_time,omitempty"`

	// StartDisplayTime corresponds to the JSON schema field "start_display_time".
	StartDisplayTime *int `json:"start_display_time,omitempty,omitzero" yaml:"start_display_time,omitempty" mapstructure:"start_display_time,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SubtitleType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["media_type"]; raw != nil && !ok {
		return fmt.Errorf("field media_type in SubtitleType: required")
	}
	type Plain SubtitleType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SubtitleType(plain)
	return nil
}

type StreamType struct {
	// AvgFrameRate corresponds to the JSON schema field "avg_frame_rate".
	AvgFrameRate string `json:"avg_frame_rate" yaml:"avg_frame_rate" mapstructure:"avg_frame_rate"`

	// BitRate corresponds to the JSON schema field "bit_rate".
	BitRate *string `json:"bit_rate,omitempty,omitzero" yaml:"bit_rate,omitempty" mapstructure:"bit_rate,omitempty"`

	// BitsPerRawSample corresponds to the JSON schema field "bits_per_raw_sample".
	BitsPerRawSample *string `json:"bits_per_raw_sample,omitempty,omitzero" yaml:"bits_per_raw_sample,omitempty" mapstructure:"bits_per_raw_sample,omitempty"`

	// BitsPerSample corresponds to the JSON schema field "bits_per_sample".
	BitsPerSample *int `json:"bits_per_sample,omitempty,omitzero" yaml:"bits_per_sample,omitempty" mapstructure:"bits_per_sample,omitempty"`

	// ChannelLayout corresponds to the JSON schema field "channel_layout".
	ChannelLayout *string `json:"channel_layout,omitempty,omitzero" yaml:"channel_layout,omitempty" mapstructure:"channel_layout,omitempty"`

	// Channels corresponds to the JSON schema field "channels".
	Channels *int `json:"channels,omitempty,omitzero" yaml:"channels,omitempty" mapstructure:"channels,omitempty"`

	// ChromaLocation corresponds to the JSON schema field "chroma_location".
	ChromaLocation *string `json:"chroma_location,omitempty,omitzero" yaml:"chroma_location,omitempty" mapstructure:"chroma_location,omitempty"`

	// ClosedCaptions corresponds to the JSON schema field "closed_captions".
	ClosedCaptions *int `json:"closed_captions,omitempty,omitzero" yaml:"closed_captions,omitempty" mapstructure:"closed_captions,omitempty"`

	// CodecLongName corresponds to the JSON schema field "codec_long_name".
	CodecLongName *string `json:"codec_long_name,omitempty,omitzero" yaml:"codec_long_name,omitempty" mapstructure:"codec_long_name,omitempty"`

	// CodecName corresponds to the JSON schema field "codec_name".
	CodecName *string `json:"codec_name,omitempty,omitzero" yaml:"codec_name,omitempty" mapstructure:"codec_name,omitempty"`

	// CodecTag corresponds to the JSON schema field "codec_tag".
	CodecTag string `json:"codec_tag" yaml:"codec_tag" mapstructure:"codec_tag"`

	// CodecTagString corresponds to the JSON schema field "codec_tag_string".
	CodecTagString string `json:"codec_tag_string" yaml:"codec_tag_string" mapstructure:"codec_tag_string"`

	// CodecType corresponds to the JSON schema field "codec_type".
	CodecType *string `json:"codec_type,omitempty,omitzero" yaml:"codec_type,omitempty" mapstructure:"codec_type,omitempty"`

	// CodedHeight corresponds to the JSON schema field "coded_height".
	CodedHeight *int `json:"coded_height,omitempty,omitzero" yaml:"coded_height,omitempty" mapstructure:"coded_height,omitempty"`

	// CodedWidth corresponds to the JSON schema field "coded_width".
	CodedWidth *int `json:"coded_width,omitempty,omitzero" yaml:"coded_width,omitempty" mapstructure:"coded_width,omitempty"`

	// ColorPrimaries corresponds to the JSON schema field "color_primaries".
	ColorPrimaries *string `json:"color_primaries,omitempty,omitzero" yaml:"color_primaries,omitempty" mapstructure:"color_primaries,omitempty"`

	// ColorRange corresponds to the JSON schema field "color_range".
	ColorRange *string `json:"color_range,omitempty,omitzero" yaml:"color_range,omitempty" mapstructure:"color_range,omitempty"`

	// ColorSpace corresponds to the JSON schema field "color_space".
	ColorSpace *string `json:"color_space,omitempty,omitzero" yaml:"color_space,omitempty" mapstructure:"color_space,omitempty"`

	// ColorTransfer corresponds to the JSON schema field "color_transfer".
	ColorTransfer *string `json:"color_transfer,omitempty,omitzero" yaml:"color_transfer,omitempty" mapstructure:"color_transfer,omitempty"`

	// DisplayAspectRatio corresponds to the JSON schema field "display_aspect_ratio".
	DisplayAspectRatio *string `json:"display_aspect_ratio,omitempty,omitzero" yaml:"display_aspect_ratio,omitempty" mapstructure:"display_aspect_ratio,omitempty"`

	// Disposition corresponds to the JSON schema field "disposition".
	Disposition *StreamDispositionType `json:"disposition,omitempty,omitzero" yaml:"disposition,omitempty" mapstructure:"disposition,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *string `json:"duration,omitempty,omitzero" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// DurationTs corresponds to the JSON schema field "duration_ts".
	DurationTs *int `json:"duration_ts,omitempty,omitzero" yaml:"duration_ts,omitempty" mapstructure:"duration_ts,omitempty"`

	// Extradata corresponds to the JSON schema field "extradata".
	Extradata *string `json:"extradata,omitempty,omitzero" yaml:"extradata,omitempty" mapstructure:"extradata,omitempty"`

	// ExtradataHash corresponds to the JSON schema field "extradata_hash".
	ExtradataHash *string `json:"extradata_hash,omitempty,omitzero" yaml:"extradata_hash,omitempty" mapstructure:"extradata_hash,omitempty"`

	// ExtradataSize corresponds to the JSON schema field "extradata_size".
	ExtradataSize *int `json:"extradata_size,omitempty,omitzero" yaml:"extradata_size,omitempty" mapstructure:"extradata_size,omitempty"`

	// FieldOrder corresponds to the JSON schema field "field_order".
	FieldOrder *string `json:"field_order,omitempty,omitzero" yaml:"field_order,omitempty" mapstructure:"field_order,omitempty"`

	// FilmGrain corresponds to the JSON schema field "film_grain".
	FilmGrain *int `json:"film_grain,omitempty,omitzero" yaml:"film_grain,omitempty" mapstructure:"film_grain,omitempty"`

	// HasBFrames corresponds to the JSON schema field "has_b_frames".
	HasBFrames *int `json:"has_b_frames,omitempty,omitzero" yaml:"has_b_frames,omitempty" mapstructure:"has_b_frames,omitempty"`

	// Height corresponds to the JSON schema field "height".
	Height *int `json:"height,omitempty,omitzero" yaml:"height,omitempty" mapstructure:"height,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *string `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Index corresponds to the JSON schema field "index".
	Index int `json:"index" yaml:"index" mapstructure:"index"`

	// InitialPadding corresponds to the JSON schema field "initial_padding".
	InitialPadding *int `json:"initial_padding,omitempty,omitzero" yaml:"initial_padding,omitempty" mapstructure:"initial_padding,omitempty"`

	// Level corresponds to the JSON schema field "level".
	Level *int `json:"level,omitempty,omitzero" yaml:"level,omitempty" mapstructure:"level,omitempty"`

	// MaxBitRate corresponds to the JSON schema field "max_bit_rate".
	MaxBitRate *string `json:"max_bit_rate,omitempty,omitzero" yaml:"max_bit_rate,omitempty" mapstructure:"max_bit_rate,omitempty"`

	// NbFrames corresponds to the JSON schema field "nb_frames".
	NbFrames *string `json:"nb_frames,omitempty,omitzero" yaml:"nb_frames,omitempty" mapstructure:"nb_frames,omitempty"`

	// NbReadFrames corresponds to the JSON schema field "nb_read_frames".
	NbReadFrames *string `json:"nb_read_frames,omitempty,omitzero" yaml:"nb_read_frames,omitempty" mapstructure:"nb_read_frames,omitempty"`

	// NbReadPackets corresponds to the JSON schema field "nb_read_packets".
	NbReadPackets *string `json:"nb_read_packets,omitempty,omitzero" yaml:"nb_read_packets,omitempty" mapstructure:"nb_read_packets,omitempty"`

	// PixFmt corresponds to the JSON schema field "pix_fmt".
	PixFmt *string `json:"pix_fmt,omitempty,omitzero" yaml:"pix_fmt,omitempty" mapstructure:"pix_fmt,omitempty"`

	// Profile corresponds to the JSON schema field "profile".
	Profile *string `json:"profile,omitempty,omitzero" yaml:"profile,omitempty" mapstructure:"profile,omitempty"`

	// RFrameRate corresponds to the JSON schema field "r_frame_rate".
	RFrameRate string `json:"r_frame_rate" yaml:"r_frame_rate" mapstructure:"r_frame_rate"`

	// Refs corresponds to the JSON schema field "refs".
	Refs *int `json:"refs,omitempty,omitzero" yaml:"refs,omitempty" mapstructure:"refs,omitempty"`

	// SampleAspectRatio corresponds to the JSON schema field "sample_aspect_ratio".
	SampleAspectRatio *string `json:"sample_aspect_ratio,omitempty,omitzero" yaml:"sample_aspect_ratio,omitempty" mapstructure:"sample_aspect_ratio,omitempty"`

	// SampleFmt corresponds to the JSON schema field "sample_fmt".
	SampleFmt *string `json:"sample_fmt,omitempty,omitzero" yaml:"sample_fmt,omitempty" mapstructure:"sample_fmt,omitempty"`

	// SampleRate corresponds to the JSON schema field "sample_rate".
	SampleRate *string `json:"sample_rate,omitempty,omitzero" yaml:"sample_rate,omitempty" mapstructure:"sample_rate,omitempty"`

	// SideDataList corresponds to the JSON schema field "side_data_list".
	SideDataList *PacketSideDataListType `json:"side_data_list,omitempty,omitzero" yaml:"side_data_list,omitempty" mapstructure:"side_data_list,omitempty"`

	// StartPts corresponds to the JSON schema field "start_pts".
	StartPts *int `json:"start_pts,omitempty,omitzero" yaml:"start_pts,omitempty" mapstructure:"start_pts,omitempty"`

	// StartTime corresponds to the JSON schema field "start_time".
	StartTime *string `json:"start_time,omitempty,omitzero" yaml:"start_time,omitempty" mapstructure:"start_time,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TimeBase corresponds to the JSON schema field "time_base".
	TimeBase string `json:"time_base" yaml:"time_base" mapstructure:"time_base"`

	// Width corresponds to the JSON schema field "width".
	Width *int `json:"width,omitempty,omitzero" yaml:"width,omitempty" mapstructure:"width,omitempty"`
}

type FfprobeTypeFramesElem_1 = SubtitleType

type StreamGroupPieceType struct {
	// PieceEntry corresponds to the JSON schema field "piece_entry".
	PieceEntry []StreamGroupEntryType `json:"piece_entry,omitempty,omitzero" yaml:"piece_entry,omitempty" mapstructure:"piece_entry,omitempty"`

	// Subpieces corresponds to the JSON schema field "subpieces".
	Subpieces *StreamGroupSubPieceList `json:"subpieces,omitempty,omitzero" yaml:"subpieces,omitempty" mapstructure:"subpieces,omitempty"`
}

type StreamGroupSubPieceList struct {
	// Subpiece corresponds to the JSON schema field "subpiece".
	Subpiece []StreamGroupSubPieceType `json:"subpiece,omitempty,omitzero" yaml:"subpiece,omitempty" mapstructure:"subpiece,omitempty"`
}

type LibraryVersionType struct {
	// Ident corresponds to the JSON schema field "ident".
	Ident string `json:"ident" yaml:"ident" mapstructure:"ident"`

	// Major corresponds to the JSON schema field "major".
	Major int `json:"major" yaml:"major" mapstructure:"major"`

	// Micro corresponds to the JSON schema field "micro".
	Micro int `json:"micro" yaml:"micro" mapstructure:"micro"`

	// Minor corresponds to the JSON schema field "minor".
	Minor int `json:"minor" yaml:"minor" mapstructure:"minor"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LibraryVersionType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ident"]; raw != nil && !ok {
		return fmt.Errorf("field ident in LibraryVersionType: required")
	}
	if _, ok := raw["major"]; raw != nil && !ok {
		return fmt.Errorf("field major in LibraryVersionType: required")
	}
	if _, ok := raw["micro"]; raw != nil && !ok {
		return fmt.Errorf("field micro in LibraryVersionType: required")
	}
	if _, ok := raw["minor"]; raw != nil && !ok {
		return fmt.Errorf("field minor in LibraryVersionType: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LibraryVersionType: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in LibraryVersionType: required")
	}
	type Plain LibraryVersionType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LibraryVersionType(plain)
	return nil
}

type PacketType struct {
	// CodecType corresponds to the JSON schema field "codec_type".
	CodecType string `json:"codec_type" yaml:"codec_type" mapstructure:"codec_type"`

	// Data corresponds to the JSON schema field "data".
	Data *string `json:"data,omitempty,omitzero" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// DataHash corresponds to the JSON schema field "data_hash".
	DataHash *string `json:"data_hash,omitempty,omitzero" yaml:"data_hash,omitempty" mapstructure:"data_hash,omitempty"`

	// Dts corresponds to the JSON schema field "dts".
	Dts *int `json:"dts,omitempty,omitzero" yaml:"dts,omitempty" mapstructure:"dts,omitempty"`

	// DtsTime corresponds to the JSON schema field "dts_time".
	DtsTime *string `json:"dts_time,omitempty,omitzero" yaml:"dts_time,omitempty" mapstructure:"dts_time,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *int `json:"duration,omitempty,omitzero" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// DurationTime corresponds to the JSON schema field "duration_time".
	DurationTime *string `json:"duration_time,omitempty,omitzero" yaml:"duration_time,omitempty" mapstructure:"duration_time,omitempty"`

	// Flags corresponds to the JSON schema field "flags".
	Flags string `json:"flags" yaml:"flags" mapstructure:"flags"`

	// Pos corresponds to the JSON schema field "pos".
	Pos *int `json:"pos,omitempty,omitzero" yaml:"pos,omitempty" mapstructure:"pos,omitempty"`

	// Pts corresponds to the JSON schema field "pts".
	Pts *int `json:"pts,omitempty,omitzero" yaml:"pts,omitempty" mapstructure:"pts,omitempty"`

	// PtsTime corresponds to the JSON schema field "pts_time".
	PtsTime *string `json:"pts_time,omitempty,omitzero" yaml:"pts_time,omitempty" mapstructure:"pts_time,omitempty"`

	// SideDataList corresponds to the JSON schema field "side_data_list".
	SideDataList *PacketSideDataListType `json:"side_data_list,omitempty,omitzero" yaml:"side_data_list,omitempty" mapstructure:"side_data_list,omitempty"`

	// Size corresponds to the JSON schema field "size".
	Size int `json:"size" yaml:"size" mapstructure:"size"`

	// StreamIndex corresponds to the JSON schema field "stream_index".
	StreamIndex int `json:"stream_index" yaml:"stream_index" mapstructure:"stream_index"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PacketType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["codec_type"]; raw != nil && !ok {
		return fmt.Errorf("field codec_type in PacketType: required")
	}
	if _, ok := raw["flags"]; raw != nil && !ok {
		return fmt.Errorf("field flags in PacketType: required")
	}
	if _, ok := raw["size"]; raw != nil && !ok {
		return fmt.Errorf("field size in PacketType: required")
	}
	if _, ok := raw["stream_index"]; raw != nil && !ok {
		return fmt.Errorf("field stream_index in PacketType: required")
	}
	type Plain PacketType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PacketType(plain)
	return nil
}

type FfprobeTypePacketsAndFramesElem_0 = PacketType

type FfprobeTypePacketsAndFramesElem_1 = FrameType

type FfprobeTypePacketsAndFramesElem_2 = SubtitleType

type StreamGroupSubPieceType struct {
	// Blocks corresponds to the JSON schema field "blocks".
	Blocks *StreamGroupBlockList `json:"blocks,omitempty,omitzero" yaml:"blocks,omitempty" mapstructure:"blocks,omitempty"`

	// SubpieceEntry corresponds to the JSON schema field "subpiece_entry".
	SubpieceEntry []StreamGroupEntryType `json:"subpiece_entry,omitempty,omitzero" yaml:"subpiece_entry,omitempty" mapstructure:"subpiece_entry,omitempty"`
}

type StreamGroupBlockList struct {
	// Block corresponds to the JSON schema field "block".
	Block []StreamGroupBlockType `json:"block,omitempty,omitzero" yaml:"block,omitempty" mapstructure:"block,omitempty"`
}

type PixelFormatComponentType struct {
	// BitDepth corresponds to the JSON schema field "bit_depth".
	BitDepth int `json:"bit_depth" yaml:"bit_depth" mapstructure:"bit_depth"`

	// Index corresponds to the JSON schema field "index".
	Index int `json:"index" yaml:"index" mapstructure:"index"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PixelFormatComponentType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bit_depth"]; raw != nil && !ok {
		return fmt.Errorf("field bit_depth in PixelFormatComponentType: required")
	}
	if _, ok := raw["index"]; raw != nil && !ok {
		return fmt.Errorf("field index in PixelFormatComponentType: required")
	}
	type Plain PixelFormatComponentType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PixelFormatComponentType(plain)
	return nil
}

type PixelFormatComponentsType struct {
	// Component corresponds to the JSON schema field "component".
	Component []PixelFormatComponentType `json:"component,omitempty,omitzero" yaml:"component,omitempty" mapstructure:"component,omitempty"`
}

type PixelFormatFlagsType struct {
	// Alpha corresponds to the JSON schema field "alpha".
	Alpha int `json:"alpha" yaml:"alpha" mapstructure:"alpha"`

	// BigEndian corresponds to the JSON schema field "big_endian".
	BigEndian int `json:"big_endian" yaml:"big_endian" mapstructure:"big_endian"`

	// Bitstream corresponds to the JSON schema field "bitstream".
	Bitstream int `json:"bitstream" yaml:"bitstream" mapstructure:"bitstream"`

	// Hwaccel corresponds to the JSON schema field "hwaccel".
	Hwaccel int `json:"hwaccel" yaml:"hwaccel" mapstructure:"hwaccel"`

	// Palette corresponds to the JSON schema field "palette".
	Palette int `json:"palette" yaml:"palette" mapstructure:"palette"`

	// Planar corresponds to the JSON schema field "planar".
	Planar int `json:"planar" yaml:"planar" mapstructure:"planar"`

	// Rgb corresponds to the JSON schema field "rgb".
	Rgb int `json:"rgb" yaml:"rgb" mapstructure:"rgb"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PixelFormatFlagsType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["alpha"]; raw != nil && !ok {
		return fmt.Errorf("field alpha in PixelFormatFlagsType: required")
	}
	if _, ok := raw["big_endian"]; raw != nil && !ok {
		return fmt.Errorf("field big_endian in PixelFormatFlagsType: required")
	}
	if _, ok := raw["bitstream"]; raw != nil && !ok {
		return fmt.Errorf("field bitstream in PixelFormatFlagsType: required")
	}
	if _, ok := raw["hwaccel"]; raw != nil && !ok {
		return fmt.Errorf("field hwaccel in PixelFormatFlagsType: required")
	}
	if _, ok := raw["palette"]; raw != nil && !ok {
		return fmt.Errorf("field palette in PixelFormatFlagsType: required")
	}
	if _, ok := raw["planar"]; raw != nil && !ok {
		return fmt.Errorf("field planar in PixelFormatFlagsType: required")
	}
	if _, ok := raw["rgb"]; raw != nil && !ok {
		return fmt.Errorf("field rgb in PixelFormatFlagsType: required")
	}
	type Plain PixelFormatFlagsType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PixelFormatFlagsType(plain)
	return nil
}

type PixelFormatType struct {
	// BitsPerPixel corresponds to the JSON schema field "bits_per_pixel".
	BitsPerPixel *int `json:"bits_per_pixel,omitempty,omitzero" yaml:"bits_per_pixel,omitempty" mapstructure:"bits_per_pixel,omitempty"`

	// Components corresponds to the JSON schema field "components".
	Components *PixelFormatComponentsType `json:"components,omitempty,omitzero" yaml:"components,omitempty" mapstructure:"components,omitempty"`

	// Flags corresponds to the JSON schema field "flags".
	Flags *PixelFormatFlagsType `json:"flags,omitempty,omitzero" yaml:"flags,omitempty" mapstructure:"flags,omitempty"`

	// Log2ChromaH corresponds to the JSON schema field "log2_chroma_h".
	Log2ChromaH *int `json:"log2_chroma_h,omitempty,omitzero" yaml:"log2_chroma_h,omitempty" mapstructure:"log2_chroma_h,omitempty"`

	// Log2ChromaW corresponds to the JSON schema field "log2_chroma_w".
	Log2ChromaW *int `json:"log2_chroma_w,omitempty,omitzero" yaml:"log2_chroma_w,omitempty" mapstructure:"log2_chroma_w,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// NbComponents corresponds to the JSON schema field "nb_components".
	NbComponents int `json:"nb_components" yaml:"nb_components" mapstructure:"nb_components"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PixelFormatType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PixelFormatType: required")
	}
	if _, ok := raw["nb_components"]; raw != nil && !ok {
		return fmt.Errorf("field nb_components in PixelFormatType: required")
	}
	type Plain PixelFormatType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PixelFormatType(plain)
	return nil
}

type ProgramVersionType struct {
	// BuildDate corresponds to the JSON schema field "build_date".
	BuildDate *string `json:"build_date,omitempty,omitzero" yaml:"build_date,omitempty" mapstructure:"build_date,omitempty"`

	// BuildTime corresponds to the JSON schema field "build_time".
	BuildTime *string `json:"build_time,omitempty,omitzero" yaml:"build_time,omitempty" mapstructure:"build_time,omitempty"`

	// CompilerIdent corresponds to the JSON schema field "compiler_ident".
	CompilerIdent string `json:"compiler_ident" yaml:"compiler_ident" mapstructure:"compiler_ident"`

	// Configuration corresponds to the JSON schema field "configuration".
	Configuration string `json:"configuration" yaml:"configuration" mapstructure:"configuration"`

	// Copyright corresponds to the JSON schema field "copyright".
	Copyright string `json:"copyright" yaml:"copyright" mapstructure:"copyright"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProgramVersionType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["compiler_ident"]; raw != nil && !ok {
		return fmt.Errorf("field compiler_ident in ProgramVersionType: required")
	}
	if _, ok := raw["configuration"]; raw != nil && !ok {
		return fmt.Errorf("field configuration in ProgramVersionType: required")
	}
	if _, ok := raw["copyright"]; raw != nil && !ok {
		return fmt.Errorf("field copyright in ProgramVersionType: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in ProgramVersionType: required")
	}
	type Plain ProgramVersionType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProgramVersionType(plain)
	return nil
}

type ProgramType struct {
	// NbStreams corresponds to the JSON schema field "nb_streams".
	NbStreams int `json:"nb_streams" yaml:"nb_streams" mapstructure:"nb_streams"`

	// PcrPid corresponds to the JSON schema field "pcr_pid".
	PcrPid int `json:"pcr_pid" yaml:"pcr_pid" mapstructure:"pcr_pid"`

	// PmtPid corresponds to the JSON schema field "pmt_pid".
	PmtPid int `json:"pmt_pid" yaml:"pmt_pid" mapstructure:"pmt_pid"`

	// ProgramId corresponds to the JSON schema field "program_id".
	ProgramId int `json:"program_id" yaml:"program_id" mapstructure:"program_id"`

	// ProgramNum corresponds to the JSON schema field "program_num".
	ProgramNum int `json:"program_num" yaml:"program_num" mapstructure:"program_num"`

	// Streams corresponds to the JSON schema field "streams".
	Streams *StreamsType `json:"streams,omitempty,omitzero" yaml:"streams,omitempty" mapstructure:"streams,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags TagsType `json:"tags,omitempty,omitzero" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProgramType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["nb_streams"]; raw != nil && !ok {
		return fmt.Errorf("field nb_streams in ProgramType: required")
	}
	if _, ok := raw["pcr_pid"]; raw != nil && !ok {
		return fmt.Errorf("field pcr_pid in ProgramType: required")
	}
	if _, ok := raw["pmt_pid"]; raw != nil && !ok {
		return fmt.Errorf("field pmt_pid in ProgramType: required")
	}
	if _, ok := raw["program_id"]; raw != nil && !ok {
		return fmt.Errorf("field program_id in ProgramType: required")
	}
	if _, ok := raw["program_num"]; raw != nil && !ok {
		return fmt.Errorf("field program_num in ProgramType: required")
	}
	type Plain ProgramType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ProgramType(plain)
	return nil
}

type StreamGroupBlockType struct {
	// BlockEntry corresponds to the JSON schema field "block_entry".
	BlockEntry []StreamGroupEntryType `json:"block_entry,omitempty,omitzero" yaml:"block_entry,omitempty" mapstructure:"block_entry,omitempty"`
}

type FramesType struct {
	// Frame corresponds to the JSON schema field "frame".
	Frame []FrameType `json:"frame,omitempty,omitzero" yaml:"frame,omitempty" mapstructure:"frame,omitempty"`

	// Subtitle corresponds to the JSON schema field "subtitle".
	Subtitle []SubtitleType `json:"subtitle,omitempty,omitzero" yaml:"subtitle,omitempty" mapstructure:"subtitle,omitempty"`
}

type LibraryVersionsType struct {
	// LibraryVersion corresponds to the JSON schema field "library_version".
	LibraryVersion []LibraryVersionType `json:"library_version,omitempty,omitzero" yaml:"library_version,omitempty" mapstructure:"library_version,omitempty"`
}

type PacketsAndFramesType struct {
	// Frame corresponds to the JSON schema field "frame".
	Frame []FrameType `json:"frame,omitempty,omitzero" yaml:"frame,omitempty" mapstructure:"frame,omitempty"`

	// Packet corresponds to the JSON schema field "packet".
	Packet []PacketType `json:"packet,omitempty,omitzero" yaml:"packet,omitempty" mapstructure:"packet,omitempty"`

	// Subtitle corresponds to the JSON schema field "subtitle".
	Subtitle []SubtitleType `json:"subtitle,omitempty,omitzero" yaml:"subtitle,omitempty" mapstructure:"subtitle,omitempty"`
}

type PacketsType struct {
	// Packet corresponds to the JSON schema field "packet".
	Packet []PacketType `json:"packet,omitempty,omitzero" yaml:"packet,omitempty" mapstructure:"packet,omitempty"`
}

type PixelFormatsType struct {
	// PixelFormat corresponds to the JSON schema field "pixel_format".
	PixelFormat []PixelFormatType `json:"pixel_format,omitempty,omitzero" yaml:"pixel_format,omitempty" mapstructure:"pixel_format,omitempty"`
}

type ProgramsType struct {
	// Program corresponds to the JSON schema field "program".
	Program []ProgramType `json:"program,omitempty,omitzero" yaml:"program,omitempty" mapstructure:"program,omitempty"`
}

type TagType struct {
	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key" mapstructure:"key"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TagType) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["key"]; raw != nil && !ok {
		return fmt.Errorf("field key in TagType: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in TagType: required")
	}
	type Plain TagType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = TagType(plain)
	return nil
}
